/**
 * book-catalog.ts — Static catalog of curated books from blas.com.
 * Provides instant load without API calls, mirrors the video-catalog pattern.
 */

export interface CatalogBook {
  id: string;
  title: string;
  author: string;
  domain: string;
  cover_url: string;
  source_url: string;
  tags: string[];
  summary: string;
  takeaways: string[];
}

export const BOOK_DOMAINS = [
  "All",
  "Business",
  "Philosophy",
  "Psychology",
  "Science",
  "Finance",
  "Self-Improvement",
  "History",
  "Technology",
  "Biography",
  "Leadership",
  "Literature",
] as const;

export type BookDomain = (typeof BOOK_DOMAINS)[number];

export const DOMAIN_COLORS: Record<string, string> = {
  Business: "from-emerald-500/20 to-green-600/20",
  Philosophy: "from-purple-500/20 to-violet-600/20",
  Psychology: "from-rose-500/20 to-pink-600/20",
  Science: "from-teal-500/20 to-cyan-600/20",
  Finance: "from-amber-500/20 to-yellow-600/20",
  "Self-Improvement": "from-orange-500/20 to-red-500/20",
  History: "from-orange-600/20 to-amber-700/20",
  Technology: "from-sky-500/20 to-indigo-600/20",
  Biography: "from-fuchsia-500/20 to-purple-600/20",
  Leadership: "from-blue-500/20 to-cyan-500/20",
  Literature: "from-amber-400/20 to-orange-500/20",
  General: "from-gray-500/20 to-slate-600/20",
};

export const FEATURED_IDS = ["the-art-of-learning", "poor-charlies-almanack", "meditations"];

export const BOOK_CATALOG: CatalogBook[] = [
  {
    id: "the-art-of-learning",
    title: "The Art of Learning",
    author: "Josh Waitzkin",
    domain: "Self-Improvement",
    cover_url: "https://i0.wp.com/blas.com/wp-content/uploads/2014/03/The-Art-of-Learning.jpg?fit=194%2C300&ssl=1",
    source_url: "https://blas.com/the-art-of-learning/",
    tags: ["mastery", "learning", "chess", "martial arts"],
    summary: "Josh Waitzkin shares his journey from chess prodigy to martial arts champion, revealing universal principles of learning and peak performance that transcend domains.",
    takeaways: ["Embrace the 'beginner's mind' to accelerate mastery", "Use adversity as fuel for deeper learning", "The key to growth is making smaller circles — internalizing fundamentals until they become second nature"],
  },
  {
    id: "poor-charlies-almanack",
    title: "Poor Charlie's Almanack",
    author: "Charlie Munger",
    domain: "Finance",
    cover_url: "https://i0.wp.com/blas.com/wp-content/uploads/2014/02/poor-charlies-almanack.jpg?fit=300%2C300&ssl=1",
    source_url: "https://blas.com/poor-charlies-almanack/",
    tags: ["investing", "mental models", "multidisciplinary", "wisdom"],
    summary: "A compendium of Charlie Munger's wit, wisdom, and investment philosophy built on mental models drawn from physics, biology, psychology, and beyond.",
    takeaways: ["Build a latticework of mental models from multiple disciplines", "Invert, always invert — avoid stupidity rather than seeking brilliance", "Circle of competence: know what you know and what you don't"],
  },
  {
    id: "meditations",
    title: "Meditations",
    author: "Marcus Aurelius",
    domain: "Philosophy",
    cover_url: "https://i0.wp.com/blas.com/wp-content/uploads/2014/02/Meditations.jpg?fit=197%2C300&ssl=1",
    source_url: "https://blas.com/meditations/",
    tags: ["stoicism", "ethics", "self-mastery", "ancient"],
    summary: "The private reflections of Roman Emperor Marcus Aurelius on duty, mortality, and the art of living — the foundational text of Stoic philosophy.",
    takeaways: ["Focus only on what you can control", "The obstacle is the way — adversity reveals character", "Memento mori: awareness of death sharpens life's meaning"],
  },
  {
    id: "thinking-fast-and-slow",
    title: "Thinking, Fast and Slow",
    author: "Daniel Kahneman",
    domain: "Psychology",
    cover_url: "https://i0.wp.com/blas.com/wp-content/uploads/2014/02/Thinking-fast-and-slow.jpg?fit=200%2C300&ssl=1",
    source_url: "https://blas.com/thinking-fast-and-slow/",
    tags: ["cognitive bias", "decision making", "behavioral economics"],
    summary: "Nobel laureate Daniel Kahneman maps the two systems that drive how we think — fast, intuitive System 1 and slow, deliberate System 2.",
    takeaways: ["We are systematically prone to cognitive biases", "System 1 is powerful but error-prone; System 2 is lazy", "Loss aversion: losses loom larger than equivalent gains"],
  },
  {
    id: "antifragile",
    title: "Antifragile",
    author: "Nassim Taleb",
    domain: "Science",
    cover_url: "https://i0.wp.com/blas.com/wp-content/uploads/2014/02/antifragile.jpg?fit=194%2C300&ssl=1",
    source_url: "https://blas.com/antifragile/",
    tags: ["complexity", "risk", "systems", "randomness"],
    summary: "Taleb introduces antifragility — systems that gain from disorder — and argues that the modern world systematically suppresses beneficial volatility.",
    takeaways: ["Some things benefit from shocks; design for antifragility", "Via negativa: improvement by removal rather than addition", "Optionality is more valuable than prediction"],
  },
  {
    id: "sapiens",
    title: "Sapiens",
    author: "Yuval Noah Harari",
    domain: "History",
    cover_url: "https://i0.wp.com/blas.com/wp-content/uploads/2015/03/sapiens.jpg?fit=190%2C300&ssl=1",
    source_url: "https://blas.com/sapiens/",
    tags: ["human history", "evolution", "civilization", "anthropology"],
    summary: "A sweeping narrative of Homo sapiens from the cognitive revolution 70,000 years ago to the present, examining how shared myths enabled global cooperation.",
    takeaways: ["Shared fictions (nations, money, religions) are humanity's superpower", "The agricultural revolution was history's biggest fraud", "Happiness hasn't increased proportionally with progress"],
  },
  {
    id: "the-innovators-dilemma",
    title: "The Innovator's Dilemma",
    author: "Clayton Christensen",
    domain: "Business",
    cover_url: "https://i0.wp.com/blas.com/wp-content/uploads/2014/02/innovators-dilemma.jpg?fit=198%2C300&ssl=1",
    source_url: "https://blas.com/the-innovators-dilemma/",
    tags: ["innovation", "disruption", "strategy", "technology"],
    summary: "Why great companies fail: Christensen shows how rational, well-managed firms are disrupted by cheaper, initially inferior technologies that improve over time.",
    takeaways: ["Sustaining vs disruptive innovation require different strategies", "Incumbents fail because they listen too well to existing customers", "Create separate organizations to pursue disruptive opportunities"],
  },
  {
    id: "mans-search-for-meaning",
    title: "Man's Search for Meaning",
    author: "Viktor Frankl",
    domain: "Philosophy",
    cover_url: "https://i0.wp.com/blas.com/wp-content/uploads/2014/02/mans-search-for-meaning.jpg?fit=191%2C300&ssl=1",
    source_url: "https://blas.com/mans-search-for-meaning/",
    tags: ["existentialism", "purpose", "suffering", "logotherapy"],
    summary: "Holocaust survivor Viktor Frankl describes how finding meaning — even in suffering — is the primary drive of human existence.",
    takeaways: ["Those who have a 'why' can bear almost any 'how'", "Freedom lies in choosing one's attitude in any circumstance", "Meaning comes through work, love, and courageous suffering"],
  },
  {
    id: "the-wealth-of-nations",
    title: "The Wealth of Nations",
    author: "Adam Smith",
    domain: "Finance",
    cover_url: "https://i0.wp.com/blas.com/wp-content/uploads/2014/07/images-5.jpg?fit=183%2C275&ssl=1",
    source_url: "https://blas.com/the-wealth-of-nations/",
    tags: ["economics", "capitalism", "markets", "trade"],
    summary: "Adam Smith's foundational work on political economy, arguing that the invisible hand of self-interest, operating in free markets, produces collective prosperity.",
    takeaways: ["Division of labor is the engine of productivity", "Self-interest, channeled through markets, serves the common good", "Free trade creates wealth for all participating nations"],
  },
  {
    id: "zero-to-one",
    title: "Zero to One",
    author: "Peter Thiel",
    domain: "Business",
    cover_url: "https://i0.wp.com/blas.com/wp-content/uploads/2014/10/zero-to-one.jpg?fit=194%2C300&ssl=1",
    source_url: "https://blas.com/zero-to-one/",
    tags: ["startups", "monopoly", "innovation", "contrarian"],
    summary: "Peter Thiel argues that the next great companies will create entirely new categories rather than competing in existing ones — going from 0 to 1 instead of 1 to n.",
    takeaways: ["Competition is for losers — seek monopoly through innovation", "Ask: what important truth do very few people agree with you on?", "Definite optimism: have a concrete plan for the future"],
  },
  {
    id: "the-selfish-gene",
    title: "The Selfish Gene",
    author: "Richard Dawkins",
    domain: "Science",
    cover_url: "https://i0.wp.com/blas.com/wp-content/uploads/2014/07/selfish-gene.jpg?fit=193%2C300&ssl=1",
    source_url: "https://blas.com/the-selfish-gene/",
    tags: ["evolution", "genetics", "biology", "memes"],
    summary: "Dawkins reframes evolution from the gene's perspective, arguing that organisms are survival machines built by genes to propagate themselves.",
    takeaways: ["Genes, not organisms, are the fundamental unit of selection", "Altruism can emerge from selfish genes through kin selection", "Memes are cultural replicators analogous to genes"],
  },
  {
    id: "influence",
    title: "Influence",
    author: "Robert Cialdini",
    domain: "Psychology",
    cover_url: "https://i0.wp.com/blas.com/wp-content/uploads/2014/02/influence.jpg?fit=194%2C300&ssl=1",
    source_url: "https://blas.com/influence/",
    tags: ["persuasion", "social psychology", "marketing", "behavior"],
    summary: "Cialdini reveals the six universal principles of persuasion — reciprocity, commitment, social proof, authority, liking, and scarcity — that drive human compliance.",
    takeaways: ["Reciprocity: people feel obligated to return favors", "Social proof: we look to others to determine correct behavior", "Scarcity creates urgency and perceived value"],
  },
  {
    id: "the-art-of-war",
    title: "The Art of War",
    author: "Sun Tzu",
    domain: "Leadership",
    cover_url: "https://i0.wp.com/blas.com/wp-content/uploads/2014/07/art-of-war.jpg?fit=199%2C300&ssl=1",
    source_url: "https://blas.com/the-art-of-war/",
    tags: ["strategy", "military", "ancient wisdom", "leadership"],
    summary: "The oldest military treatise in the world, Sun Tzu's principles of strategy, deception, and adaptability remain relevant in business, politics, and life.",
    takeaways: ["Know yourself and know your enemy — victory in every battle", "The supreme art of war is to subdue the enemy without fighting", "Appear weak when you are strong, and strong when you are weak"],
  },
  {
    id: "the-hard-thing-about-hard-things",
    title: "The Hard Thing About Hard Things",
    author: "Ben Horowitz",
    domain: "Business",
    cover_url: "https://i0.wp.com/blas.com/wp-content/uploads/2014/05/the-hard-thing-about-hard-things.jpg?fit=200%2C300&ssl=1",
    source_url: "https://blas.com/the-hard-thing-about-hard-things/",
    tags: ["startups", "management", "leadership", "venture capital"],
    summary: "Ben Horowitz shares brutally honest advice on the hardest problems in building a company — the ones nobody prepares you for.",
    takeaways: ["There is no recipe for hard decisions — embrace the struggle", "Take care of the people, the products, and the profits — in that order", "Peacetime CEO vs wartime CEO require fundamentally different approaches"],
  },
  {
    id: "the-master-and-his-emissary",
    title: "The Master and His Emissary",
    author: "Iain McGilchrist",
    domain: "Science",
    cover_url: "https://i0.wp.com/blas.com/wp-content/uploads/2017/06/Master-and-his-Emissary.jpg?fit=198%2C300&ssl=1",
    source_url: "https://blas.com/the-master-and-his-emissary/",
    tags: ["neuroscience", "brain hemispheres", "philosophy", "culture"],
    summary: "McGilchrist argues that the two brain hemispheres have fundamentally different ways of attending to the world, and Western civilization has over-privileged the left hemisphere's narrow focus.",
    takeaways: ["The right hemisphere grasps the whole; the left hemisphere dissects parts", "Western civilization's crisis stems from left-hemisphere dominance", "True understanding requires holding both perspectives simultaneously"],
  },
  {
    id: "tao-te-ching",
    title: "Tao Te Ching",
    author: "Lao Tzu",
    domain: "Philosophy",
    cover_url: "https://i0.wp.com/blas.com/wp-content/uploads/2014/07/tao-te-ching.jpg?fit=197%2C300&ssl=1",
    source_url: "https://blas.com/tao-te-ching/",
    tags: ["taoism", "eastern philosophy", "wisdom", "simplicity"],
    summary: "The foundational text of Taoism in 81 poetic verses, exploring the nature of the Tao (the Way) — effortless action, simplicity, and harmony with nature.",
    takeaways: ["Wu wei: act without forcing; achieve without striving", "The softest thing overcomes the hardest", "The Tao that can be spoken is not the eternal Tao"],
  },
  {
    id: "good-to-great",
    title: "Good to Great",
    author: "Jim Collins",
    domain: "Business",
    cover_url: "https://i0.wp.com/blas.com/wp-content/uploads/2014/02/good-to-great.jpg?fit=199%2C300&ssl=1",
    source_url: "https://blas.com/good-to-great/",
    tags: ["management", "leadership", "strategy", "excellence"],
    summary: "Collins identifies what separates companies that make the leap from good to great: Level 5 leadership, the Hedgehog Concept, and a culture of discipline.",
    takeaways: ["Level 5 leaders combine personal humility with professional will", "The Hedgehog Concept: find the intersection of passion, skill, and economics", "First who, then what — get the right people on the bus"],
  },
  {
    id: "surely-youre-joking-mr-feynman",
    title: "Surely You're Joking, Mr. Feynman!",
    author: "Richard Feynman",
    domain: "Biography",
    cover_url: "https://i0.wp.com/blas.com/wp-content/uploads/2014/02/surely-youre-joking.jpg?fit=200%2C300&ssl=1",
    source_url: "https://blas.com/surely-youre-joking-mr-feynman/",
    tags: ["physics", "curiosity", "adventure", "humor"],
    summary: "Nobel physicist Richard Feynman's wildly entertaining autobiography — from cracking safes at Los Alamos to bongo-drumming in Brazil, fueled by insatiable curiosity.",
    takeaways: ["Curiosity-driven exploration leads to the deepest insights", "Don't fool yourself — and you are the easiest person to fool", "The joy of discovery is the greatest reward"],
  },
  {
    id: "flow",
    title: "Flow",
    author: "Mihaly Csikszentmihalyi",
    domain: "Psychology",
    cover_url: "https://i0.wp.com/blas.com/wp-content/uploads/2014/02/flow.jpg?fit=200%2C300&ssl=1",
    source_url: "https://blas.com/flow/",
    tags: ["peak performance", "happiness", "creativity", "consciousness"],
    summary: "Csikszentmihalyi defines 'flow' — the state of complete absorption in a challenging activity — as the key to optimal experience and genuine happiness.",
    takeaways: ["Flow occurs when challenge level matches skill level", "Autotelic personality: find intrinsic reward in the activity itself", "Controlling consciousness is the path to happiness, not external rewards"],
  },
  {
    id: "the-intelligent-investor",
    title: "The Intelligent Investor",
    author: "Benjamin Graham",
    domain: "Finance",
    cover_url: "https://i0.wp.com/blas.com/wp-content/uploads/2014/02/the-intelligent-investor.jpg?fit=197%2C300&ssl=1",
    source_url: "https://blas.com/the-intelligent-investor/",
    tags: ["value investing", "stock market", "margin of safety"],
    summary: "Benjamin Graham's classic on value investing teaches the principles of margin of safety, Mr. Market's mood swings, and the difference between investing and speculating.",
    takeaways: ["Margin of safety: buy significantly below intrinsic value", "Mr. Market is your servant, not your guide", "Investment is most intelligent when it is most businesslike"],
  },
  {
    id: "the-bhagavad-gita",
    title: "The Bhagavad Gita",
    author: "Eknath Easwaran (trans.)",
    domain: "Philosophy",
    cover_url: "https://i0.wp.com/blas.com/wp-content/uploads/2014/10/gita.jpg?fit=195%2C300&ssl=1",
    source_url: "https://blas.com/the-bhagavad-gita/",
    tags: ["hinduism", "dharma", "spirituality", "duty"],
    summary: "The 700-verse Hindu scripture — a dialogue between prince Arjuna and the god Krishna on duty, righteousness, and the nature of self.",
    takeaways: ["Act without attachment to the fruits of action", "The self is eternal; the body is temporary", "Equanimity in success and failure is the mark of a yogi"],
  },
  {
    id: "principles",
    title: "Principles",
    author: "Ray Dalio",
    domain: "Business",
    cover_url: "https://i0.wp.com/blas.com/wp-content/uploads/2017/10/Principles.jpg?fit=200%2C300&ssl=1",
    source_url: "https://blas.com/principles/",
    tags: ["management", "decision making", "radical transparency", "systems"],
    summary: "Bridgewater founder Ray Dalio shares the principles that guided his life and built the world's largest hedge fund — radical truth, radical transparency, and systematic decision-making.",
    takeaways: ["Pain + reflection = progress", "Embrace radical transparency and idea meritocracy", "Build decision-making machines using principles as algorithms"],
  },
  {
    id: "on-the-shortness-of-life",
    title: "On the Shortness of Life",
    author: "Seneca",
    domain: "Philosophy",
    cover_url: "https://i0.wp.com/blas.com/wp-content/uploads/2014/02/on-the-shortness-of-life.jpg?fit=188%2C300&ssl=1",
    source_url: "https://blas.com/on-the-shortness-of-life/",
    tags: ["stoicism", "time", "mortality", "wisdom"],
    summary: "Seneca argues that life is long enough if we use it wisely — most people waste their time on trivial pursuits and only realize its value when death approaches.",
    takeaways: ["Life is long if you know how to use it", "We waste time as if it were infinite, yet guard money jealously", "The present is the only time we truly possess"],
  },
  {
    id: "the-lessons-of-history",
    title: "The Lessons of History",
    author: "Will & Ariel Durant",
    domain: "History",
    cover_url: "https://i0.wp.com/blas.com/wp-content/uploads/2014/02/lessons-of-history.jpg?fit=198%2C300&ssl=1",
    source_url: "https://blas.com/the-lessons-of-history/",
    tags: ["civilization", "patterns", "philosophy of history"],
    summary: "The Durants distill their 11-volume Story of Civilization into 100 pages of essential patterns in biology, economics, religion, morals, war, and government.",
    takeaways: ["Inequality is natural but concentration triggers revolution", "History is a race between education and catastrophe", "Freedom and equality are eternal enemies — more of one means less of the other"],
  },
  {
    id: "the-almanack-of-naval-ravikant",
    title: "The Almanack of Naval Ravikant",
    author: "Eric Jorgenson",
    domain: "Self-Improvement",
    cover_url: "https://i0.wp.com/blas.com/wp-content/uploads/2020/10/Naval.jpg?fit=200%2C300&ssl=1",
    source_url: "https://blas.com/the-almanack-of-naval-ravikant/",
    tags: ["wealth", "happiness", "philosophy", "startups"],
    summary: "A curated guide to Naval Ravikant's wisdom on building wealth, finding happiness, and living a meaningful life through leverage, specific knowledge, and accountability.",
    takeaways: ["Seek wealth, not money or status — wealth is having assets that earn while you sleep", "Specific knowledge + leverage + accountability = outsized returns", "Happiness is a choice and a skill, not a destination"],
  },
  {
    id: "mastery",
    title: "Mastery",
    author: "Robert Greene",
    domain: "Self-Improvement",
    cover_url: "https://i0.wp.com/blas.com/wp-content/uploads/2014/02/mastery.jpg?fit=193%2C300&ssl=1",
    source_url: "https://blas.com/mastery/",
    tags: ["apprenticeship", "creativity", "genius", "practice"],
    summary: "Robert Greene deconstructs the path to mastery through the lives of historical greats — Leonardo da Vinci, Darwin, Mozart — revealing the universal apprenticeship pattern.",
    takeaways: ["The apprenticeship phase is non-negotiable — submit to learn", "Combine multiple skills into a unique creative niche", "Intuition is the ultimate form of intelligence, built through deep practice"],
  },
  {
    id: "the-beginning-of-infinity",
    title: "The Beginning of Infinity",
    author: "David Deutsch",
    domain: "Science",
    cover_url: "https://i0.wp.com/blas.com/wp-content/uploads/2016/10/The-Beginning-of-Infinity-2.jpg?fit=200%2C300&ssl=1",
    source_url: "https://blas.com/the-beginning-of-infinity/",
    tags: ["epistemology", "physics", "progress", "explanation"],
    summary: "Physicist David Deutsch argues that good explanations — testable, hard to vary — are the engine of infinite progress, and that humans are universal explainers.",
    takeaways: ["Problems are inevitable but soluble — the beginning of infinity", "Good explanations are hard to vary while still fitting the data", "Humans are universal constructors and universal explainers"],
  },
  {
    id: "48-laws-of-power",
    title: "The 48 Laws of Power",
    author: "Robert Greene",
    domain: "Leadership",
    cover_url: "https://i0.wp.com/blas.com/wp-content/uploads/2014/02/48-laws-of-power.jpg?fit=193%2C300&ssl=1",
    source_url: "https://blas.com/the-48-laws-of-power/",
    tags: ["strategy", "power", "history", "human nature"],
    summary: "Greene distills 3,000 years of power dynamics into 48 laws drawn from the lives of Machiavelli, Sun Tzu, Louis XIV, and other masters of strategy.",
    takeaways: ["Never outshine the master", "Conceal your intentions; use selective honesty", "Make other people come to you — use bait if necessary"],
  },
  {
    id: "shoe-dog",
    title: "Shoe Dog",
    author: "Phil Knight",
    domain: "Biography",
    cover_url: "https://i0.wp.com/blas.com/wp-content/uploads/2016/06/shoe-dog.jpg?fit=194%2C300&ssl=1",
    source_url: "https://blas.com/shoe-dog/",
    tags: ["Nike", "entrepreneurship", "memoir", "business"],
    summary: "Phil Knight's memoir of building Nike from a crazy idea to a global brand — full of near-death experiences, wild risks, and relentless belief.",
    takeaways: ["Don't stop — whatever you do, just don't stop", "The cowards never started and the weak died along the way", "Believe in the product, believe in the mission"],
  },
  {
    id: "the-tao-of-pooh",
    title: "The Tao of Pooh",
    author: "Benjamin Hoff",
    domain: "Philosophy",
    cover_url: "https://i0.wp.com/blas.com/wp-content/uploads/2014/07/tao-of-pooh.jpg?fit=199%2C300&ssl=1",
    source_url: "https://blas.com/the-tao-of-pooh/",
    tags: ["taoism", "simplicity", "children", "wisdom"],
    summary: "Benjamin Hoff uses Winnie-the-Pooh to explain the principles of Taoism — showing that Pooh's simple, easygoing nature embodies the Tao perfectly.",
    takeaways: ["The Uncarved Block: simplicity and natural potential", "Things just happen in the right way at the right time", "Cleverness and knowledge often get in the way of wisdom"],
  },
  {
    id: "the-outsiders",
    title: "The Outsiders",
    author: "William Thorndike",
    domain: "Finance",
    cover_url: "https://i0.wp.com/blas.com/wp-content/uploads/2014/02/the-outsiders.jpg?fit=200%2C300&ssl=1",
    source_url: "https://blas.com/the-outsiders/",
    tags: ["capital allocation", "CEOs", "investing", "management"],
    summary: "Thorndike profiles eight unconventional CEOs who delivered extraordinary returns through rational, independent capital allocation rather than following the crowd.",
    takeaways: ["Capital allocation is the CEO's most important job", "Per-share value matters more than total revenue or earnings growth", "Decentralize operations but centralize capital allocation"],
  },
  {
    id: "letters-from-a-stoic",
    title: "Letters from a Stoic",
    author: "Seneca",
    domain: "Philosophy",
    cover_url: "https://i0.wp.com/blas.com/wp-content/uploads/2014/02/letters-from-a-stoic.jpg?fit=190%2C300&ssl=1",
    source_url: "https://blas.com/letters-from-a-stoic/",
    tags: ["stoicism", "ethics", "wisdom", "philosophy"],
    summary: "Seneca's 124 letters to Lucilius offer practical Stoic wisdom on friendship, death, wealth, anger, and the good life.",
    takeaways: ["We suffer more in imagination than in reality", "Set aside time each day for philosophical reflection", "True wealth is wanting less, not having more"],
  },
  {
    id: "siddhartha",
    title: "Siddhartha",
    author: "Hermann Hesse",
    domain: "Literature",
    cover_url: "https://i0.wp.com/blas.com/wp-content/uploads/2014/07/siddhartha.jpg?fit=199%2C300&ssl=1",
    source_url: "https://blas.com/siddhartha/",
    tags: ["buddhism", "self-discovery", "spirituality", "novel"],
    summary: "Hermann Hesse's novel follows Siddhartha's spiritual journey through asceticism, wealth, and love to find enlightenment beside a river.",
    takeaways: ["Wisdom cannot be taught — it must be experienced", "The river teaches: everything returns, all is connected", "Seeking too hard for meaning prevents finding it"],
  },
  {
    id: "deep-work",
    title: "Deep Work",
    author: "Cal Newport",
    domain: "Self-Improvement",
    cover_url: "https://i0.wp.com/blas.com/wp-content/uploads/2016/03/deep-work.jpg?fit=197%2C300&ssl=1",
    source_url: "https://blas.com/deep-work/",
    tags: ["productivity", "focus", "concentration", "career"],
    summary: "Cal Newport argues that the ability to perform deep, focused work is becoming increasingly rare and increasingly valuable in the knowledge economy.",
    takeaways: ["Deep work is the superpower of the 21st century", "Schedule every minute of your day; embrace boredom", "Quit social media — or at least apply the craftsman approach"],
  },
  {
    id: "the-republic",
    title: "The Republic",
    author: "Plato",
    domain: "Philosophy",
    cover_url: "https://i0.wp.com/blas.com/wp-content/uploads/2014/07/republic.jpg?fit=186%2C300&ssl=1",
    source_url: "https://blas.com/the-republic/",
    tags: ["justice", "ideal state", "philosophy", "ancient Greece"],
    summary: "Plato's masterwork on justice, the ideal state, and the nature of reality — featuring the Allegory of the Cave and the philosopher-king concept.",
    takeaways: ["Justice is harmony — each part performing its proper function", "The Allegory of the Cave: most people mistake shadows for reality", "Philosopher-kings: those who know truth should govern"],
  },
  {
    id: "scale",
    title: "Scale",
    author: "Geoffrey West",
    domain: "Science",
    cover_url: "https://i0.wp.com/blas.com/wp-content/uploads/2017/06/Scale.jpg?fit=199%2C300&ssl=1",
    source_url: "https://blas.com/scale/",
    tags: ["complexity", "physics", "biology", "cities", "power laws"],
    summary: "Physicist Geoffrey West reveals universal scaling laws that govern organisms, cities, and companies — from metabolic rates to urban innovation.",
    takeaways: ["Biology scales sublinearly: bigger animals are more efficient but slower", "Cities scale superlinearly: doubling size increases innovation by ~15%", "Companies scale sublinearly like organisms — they eventually die"],
  },
  {
    id: "the-structure-of-scientific-revolutions",
    title: "The Structure of Scientific Revolutions",
    author: "Thomas Kuhn",
    domain: "Science",
    cover_url: "https://i0.wp.com/blas.com/wp-content/uploads/2014/07/structure-of-sci-revolutions.jpg?fit=197%2C300&ssl=1",
    source_url: "https://blas.com/the-structure-of-scientific-revolutions/",
    tags: ["paradigm shift", "epistemology", "philosophy of science"],
    summary: "Kuhn argues that science doesn't progress linearly but through paradigm shifts — revolutionary changes in worldview that redefine what counts as valid knowledge.",
    takeaways: ["Normal science works within paradigms; anomalies accumulate", "Paradigm shifts are revolutionary, not incremental", "Scientists in different paradigms literally see different worlds"],
  },
  {
    id: "the-book-of-five-rings",
    title: "The Book of Five Rings",
    author: "Miyamoto Musashi",
    domain: "Leadership",
    cover_url: "https://i0.wp.com/blas.com/wp-content/uploads/2014/07/book-of-five-rings.jpg?fit=195%2C300&ssl=1",
    source_url: "https://blas.com/the-book-of-five-rings/",
    tags: ["strategy", "martial arts", "samurai", "discipline"],
    summary: "Legendary samurai Miyamoto Musashi's treatise on strategy, combat, and the Way — written after 60 duels and a lifetime of martial mastery.",
    takeaways: ["Know the Way broadly and you will see it in all things", "Do nothing that is of no use — eliminate waste", "In strategy, timing is everything"],
  },
  {
    id: "atomic-habits",
    title: "Atomic Habits",
    author: "James Clear",
    domain: "Self-Improvement",
    cover_url: "https://i0.wp.com/blas.com/wp-content/uploads/2019/01/Atomic-Habits.jpg?fit=197%2C300&ssl=1",
    source_url: "https://blas.com/atomic-habits/",
    tags: ["habits", "behavior change", "identity", "systems"],
    summary: "James Clear reveals how tiny changes in habits compound into remarkable results, using a four-step framework: cue, craving, response, reward.",
    takeaways: ["1% better every day compounds to 37x over a year", "Focus on identity, not outcomes — become the type of person", "Make good habits obvious, attractive, easy, and satisfying"],
  },
  {
    id: "godel-escher-bach",
    title: "Godel, Escher, Bach",
    author: "Douglas Hofstadter",
    domain: "Science",
    cover_url: "https://i0.wp.com/blas.com/wp-content/uploads/2014/02/godel-escher-bach.jpg?fit=187%2C300&ssl=1",
    source_url: "https://blas.com/godel-escher-bach/",
    tags: ["consciousness", "recursion", "mathematics", "art", "AI"],
    summary: "Hofstadter weaves together Godel's incompleteness theorems, Escher's recursive art, and Bach's fugues to explore the nature of consciousness and self-reference.",
    takeaways: ["Strange loops and self-reference are the key to consciousness", "Formal systems cannot capture all truths about themselves", "Isomorphisms connect apparently disparate domains"],
  },
  {
    id: "the-undoing-project",
    title: "The Undoing Project",
    author: "Michael Lewis",
    domain: "Psychology",
    cover_url: "https://i0.wp.com/blas.com/wp-content/uploads/2017/03/The-Undoing-Project.jpg?fit=200%2C300&ssl=1",
    source_url: "https://blas.com/the-undoing-project/",
    tags: ["behavioral economics", "friendship", "Kahneman", "Tversky"],
    summary: "Michael Lewis tells the story of Daniel Kahneman and Amos Tversky's extraordinary intellectual partnership that revolutionized how we understand human judgment.",
    takeaways: ["The best collaborations create something neither person could alone", "Our intuitions are systematically biased in predictable ways", "The mind is a brilliant pattern-matcher that often over-matches"],
  },
  {
    id: "the-emperor-of-all-maladies",
    title: "The Emperor of All Maladies",
    author: "Siddhartha Mukherjee",
    domain: "Science",
    cover_url: "https://i0.wp.com/blas.com/wp-content/uploads/2015/10/emperor-of-all-maladies.jpg?fit=197%2C300&ssl=1",
    source_url: "https://blas.com/the-emperor-of-all-maladies/",
    tags: ["cancer", "medicine", "history", "biology"],
    summary: "A 'biography' of cancer — from ancient Egypt to modern immunotherapy — revealing cancer as the most relentless and adaptive enemy in medical history.",
    takeaways: ["Cancer is not one disease but many, each with unique genetics", "The war on cancer required fundamental biological understanding, not just drugs", "Prevention and early detection remain the most powerful weapons"],
  },
  {
    id: "skin-in-the-game",
    title: "Skin in the Game",
    author: "Nassim Taleb",
    domain: "Philosophy",
    cover_url: "https://i0.wp.com/blas.com/wp-content/uploads/2018/04/Skin-in-the-Game.jpg?fit=197%2C300&ssl=1",
    source_url: "https://blas.com/skin-in-the-game/",
    tags: ["risk", "ethics", "asymmetry", "systems"],
    summary: "Taleb argues that having skin in the game — bearing consequences of your decisions — is the foundation of ethics, risk management, and a functioning society.",
    takeaways: ["Never trust anyone who doesn't have skin in the game", "Symmetry in risk-taking is essential for fairness and survival", "The minority rule: intolerant minorities can dictate societal choices"],
  },
  {
    id: "the-power-of-now",
    title: "The Power of Now",
    author: "Eckhart Tolle",
    domain: "Self-Improvement",
    cover_url: "https://i0.wp.com/blas.com/wp-content/uploads/2014/07/power-of-now.jpg?fit=200%2C300&ssl=1",
    source_url: "https://blas.com/the-power-of-now/",
    tags: ["mindfulness", "presence", "consciousness", "spirituality"],
    summary: "Tolle teaches that enlightenment is available in the present moment — the incessant stream of thinking is the primary obstacle to peace.",
    takeaways: ["You are not your thoughts — observe them without identification", "The present moment is all you ever have", "The pain-body: accumulated emotional pain feeds on negative thinking"],
  },
  {
    id: "100-baggers",
    title: "100 Baggers",
    author: "Christopher Mayer",
    domain: "Finance",
    cover_url: "https://i0.wp.com/blas.com/wp-content/uploads/2016/03/100-Baggers.jpg?fit=197%2C300&ssl=1",
    source_url: "https://blas.com/100-baggers/",
    tags: ["investing", "compounding", "patience", "growth stocks"],
    summary: "Mayer studies stocks that returned 100x and identifies the common traits: small size, long runway for growth, high returns on capital, and patient shareholders.",
    takeaways: ["The key to 100-baggers is time — you must hold for years", "Look for companies with high ROIC and long reinvestment runways", "The coffee-can portfolio: buy great companies and forget about them"],
  },
];
