/**
 * knowledge-lenses — Lens blueprint system for the knowledge renderer.
 *
 * Each lens is a transparent, editable "recipe" with tunable parameters
 * that control how content is synthesized. Presets are built-in; dynamic
 * lenses are generated by the intelligence engine from user behavior.
 */

/* ── Blueprint Parameter Types ── */

export type LensTone = "neutral" | "vivid" | "technical" | "conversational" | "poetic";
export type LensDepth = "overview" | "standard" | "deep" | "exhaustive";
export type LensAudience = "beginner" | "curious" | "informed" | "expert";
export type LensStructure = "sections" | "narrative" | "qa" | "timeline" | "comparison";
export type LensCitationDensity = "minimal" | "moderate" | "thorough";

export interface LensParams {
  tone: LensTone;
  depth: LensDepth;
  audience: LensAudience;
  structure: LensStructure;
  citationDensity: LensCitationDensity;
  focusAreas: string[];
  excludeAreas: string[];
}

export interface RecommendedSource {
  domain: string;
  reason: string;
  qualityScore: number;
  enabled: boolean;
}

export interface LensBlueprint {
  id: string;
  label: string;
  icon: "BookOpen" | "Newspaper" | "Baby" | "GraduationCap" | "BookText" | "Sparkles" | "User" | "Calculator";
  description: string;
  isPreset: boolean;
  /** Human-readable reason for AI-generated lenses */
  generatedReason?: string;
  /** The tunable recipe */
  params: LensParams;
  /** High-signal sources recommended for this lens */
  recommendedSources?: RecommendedSource[];
}

/* ── Legacy compat type ── */
export interface KnowledgeLens {
  id: string;
  label: string;
  icon: "BookOpen" | "Newspaper" | "Baby" | "GraduationCap" | "BookText" | "Calculator";
  description: string;
}

/* ── Preset Blueprints ── */

export const PRESET_BLUEPRINTS: LensBlueprint[] = [
  {
    id: "encyclopedia",
    label: "Encyclopedia",
    icon: "BookOpen",
    description: "Neutral, Wikipedia-style article with structured sections",
    isPreset: true,
    params: {
      tone: "neutral",
      depth: "standard",
      audience: "curious",
      structure: "sections",
      citationDensity: "thorough",
      focusAreas: [],
      excludeAreas: [],
    },
    recommendedSources: [
      { domain: "wikipedia.org", reason: "Gold-standard encyclopedic source", qualityScore: 98, enabled: true },
      { domain: "britannica.com", reason: "Authoritative reference", qualityScore: 95, enabled: true },
      { domain: "plato.stanford.edu", reason: "Peer-reviewed philosophy encyclopedia", qualityScore: 96, enabled: true },
      { domain: "scholar.google.com", reason: "Broad academic search across disciplines", qualityScore: 93, enabled: true },
      { domain: "pubmed.ncbi.nlm.nih.gov", reason: "US National Library of Medicine — biomedical research", qualityScore: 96, enabled: true },
      { domain: "loc.gov", reason: "Library of Congress — primary sources and reference", qualityScore: 94, enabled: true },
      { domain: "jstor.org", reason: "Digital library of academic journals and books", qualityScore: 92, enabled: true },
      { domain: "worldcat.org", reason: "World's largest library catalog (OCLC)", qualityScore: 90, enabled: true },
    ],
  },
  {
    id: "magazine",
    label: "Magazine",
    icon: "Newspaper",
    description: "Vivid feature article with dramatic flair and pull quotes",
    isPreset: true,
    params: {
      tone: "vivid",
      depth: "standard",
      audience: "curious",
      structure: "narrative",
      citationDensity: "minimal",
      focusAreas: ["human interest", "cultural impact"],
      excludeAreas: [],
    },
    recommendedSources: [
      { domain: "theatlantic.com", reason: "Premium long-form journalism", qualityScore: 74, enabled: true },
      { domain: "nationalgeographic.com", reason: "Visual storytelling authority", qualityScore: 78, enabled: true },
    ],
  },
  {
    id: "explain-like-5",
    label: "Simple",
    icon: "Baby",
    description: "Explained for a curious 8-year-old — analogies and wonder",
    isPreset: true,
    params: {
      tone: "conversational",
      depth: "overview",
      audience: "beginner",
      structure: "qa",
      citationDensity: "minimal",
      focusAreas: ["analogies", "everyday examples", "wonder"],
      excludeAreas: ["mathematical proofs", "technical jargon"],
    },
  },
  {
    id: "expert",
    label: "Deep Dive",
    icon: "GraduationCap",
    description: "Graduate-level technical depth for domain experts",
    isPreset: true,
    params: {
      tone: "technical",
      depth: "exhaustive",
      audience: "expert",
      structure: "sections",
      citationDensity: "thorough",
      focusAreas: ["theoretical frameworks", "quantitative analysis", "open problems"],
      excludeAreas: ["basic definitions"],
    },
    recommendedSources: [
      { domain: "arxiv.org", reason: "Preprint research papers", qualityScore: 96, enabled: true },
      { domain: "nature.com", reason: "Top-tier peer-reviewed science", qualityScore: 97, enabled: true },
      { domain: "scholar.google.com", reason: "Broad academic search", qualityScore: 93, enabled: true },
    ],
  },
  {
    id: "storyteller",
    label: "Story",
    icon: "BookText",
    description: "Narrative arc — told as a compelling story with drama",
    isPreset: true,
    params: {
      tone: "poetic",
      depth: "standard",
      audience: "curious",
      structure: "narrative",
      citationDensity: "minimal",
      focusAreas: ["human stories", "historical moments", "dramatic tension"],
      excludeAreas: [],
    },
    recommendedSources: [
      { domain: "smithsonianmag.com", reason: "History and culture storytelling", qualityScore: 78, enabled: true },
    ],
  },
  {
    id: "compute",
    label: "Compute",
    icon: "Calculator",
    description: "Wolfram Alpha-style computational pods — live calculations, properties, and data",
    isPreset: true,
    params: {
      tone: "technical",
      depth: "standard",
      audience: "informed",
      structure: "sections",
      citationDensity: "moderate",
      focusAreas: ["quantitative data", "computations", "properties", "comparisons"],
      excludeAreas: ["narrative", "history"],
    },
    recommendedSources: [
      { domain: "wolframalpha.com", reason: "Computational knowledge engine", qualityScore: 99, enabled: true },
    ],
  },
];

/** Legacy flat array for backward compat */
export const KNOWLEDGE_LENSES: KnowledgeLens[] = PRESET_BLUEPRINTS.map(b => ({
  id: b.id,
  label: b.label,
  icon: b.icon as KnowledgeLens["icon"],
  description: b.description,
}));

export const DEFAULT_LENS = "encyclopedia";

export function getLens(id: string): KnowledgeLens {
  return KNOWLEDGE_LENSES.find((l) => l.id === id) ?? KNOWLEDGE_LENSES[0];
}

export function getBlueprint(id: string): LensBlueprint {
  return PRESET_BLUEPRINTS.find((b) => b.id === id) ?? PRESET_BLUEPRINTS[0];
}

/** Create a deep copy of a blueprint for editing */
export function cloneBlueprint(bp: LensBlueprint): LensBlueprint {
  return JSON.parse(JSON.stringify(bp));
}

/* ── User-saved custom lenses (localStorage) ── */

const CUSTOM_LENSES_KEY = "uor:custom-lenses";

export function loadCustomLenses(): LensBlueprint[] {
  try {
    const raw = localStorage.getItem(CUSTOM_LENSES_KEY);
    if (!raw) return [];
    return JSON.parse(raw);
  } catch {
    return [];
  }
}

export function saveCustomLens(bp: LensBlueprint): void {
  const existing = loadCustomLenses();
  const idx = existing.findIndex(l => l.id === bp.id);
  if (idx >= 0) existing[idx] = bp;
  else existing.push(bp);
  localStorage.setItem(CUSTOM_LENSES_KEY, JSON.stringify(existing));
}

export function deleteCustomLens(id: string): void {
  const existing = loadCustomLenses().filter(l => l.id !== id);
  localStorage.setItem(CUSTOM_LENSES_KEY, JSON.stringify(existing));
}

/* ── Human-readable parameter labels ── */

export const TONE_OPTIONS: Array<{ value: LensTone; label: string; emoji: string }> = [
  { value: "neutral", label: "Neutral", emoji: "📋" },
  { value: "vivid", label: "Vivid", emoji: "🎨" },
  { value: "technical", label: "Technical", emoji: "⚙️" },
  { value: "conversational", label: "Casual", emoji: "💬" },
  { value: "poetic", label: "Poetic", emoji: "✨" },
];

export const DEPTH_OPTIONS: Array<{ value: LensDepth; label: string }> = [
  { value: "overview", label: "Overview" },
  { value: "standard", label: "Standard" },
  { value: "deep", label: "Deep" },
  { value: "exhaustive", label: "Exhaustive" },
];

export const AUDIENCE_OPTIONS: Array<{ value: LensAudience; label: string }> = [
  { value: "beginner", label: "Beginner" },
  { value: "curious", label: "Curious" },
  { value: "informed", label: "Informed" },
  { value: "expert", label: "Expert" },
];

export const STRUCTURE_OPTIONS: Array<{ value: LensStructure; label: string }> = [
  { value: "sections", label: "Sections" },
  { value: "narrative", label: "Narrative" },
  { value: "qa", label: "Q & A" },
  { value: "timeline", label: "Timeline" },
  { value: "comparison", label: "Comparison" },
];
