/**
 * UOR Receipt Registry — Canonical store for WASM-enriched receipts.
 *
 * Every receipt generated by the Oracle passes through the WASM Rust ring
 * engine (uor-foundation crate) to produce an algebraic signature.
 * This registry stores source objects + enriched receipts for cross-page lookup.
 */

import { getEngine } from "@/modules/kernel/engine";
import { singleProofHash, type SingleProofResult } from "@/lib/uor-canonical";
import { canonicalToTriword, formatTriword, triwordBreakdown, isValidTriword, triwordToPrefix } from "@/lib/uor-triword";
import { supabase } from "@/integrations/supabase/client";

// ── Enriched Receipt (WASM-anchored) ───────────────────────────────────────

export interface EnrichedReceipt {
  /** CIDv1 / dag-json / sha2-256 / base32lower */
  cid: string;
  /** urn:uor:derivation:sha256:{hex64} */
  derivationId: string;
  /** Braille glyph bijection */
  glyph: string;
  /** Content-addressed IPv6 ULA */
  ipv6: string;
  /** Raw hex of SHA-256 */
  hashHex: string;
  /** URDNA2015 canonical N-Quads */
  nquads: string;

  // ── WASM Ring Algebraic Signature ──
  /** First byte of the SHA-256 hash — the ring element */
  ringByte: number;
  /** Ring partition classification (e.g. "Irreducible", "PrimePower") */
  ringPartition: string;
  /** Prime factorization of the ring byte */
  ringFactors: number[];
  /** Whether the critical identity (x ⊕ ¬x = 0xFF) holds for this byte */
  ringCriticalIdentity: boolean;
  /** Popcount (Hamming weight) of the ring byte */
  ringPopcount: number;
  /** Basis elements of the ring byte */
  ringBasis: number[];
  /** "wasm" or "typescript" — which engine computed the ring data */
  engine: "wasm" | "typescript";
  /** Crate version if WASM, null if TS fallback */
  crateVersion: string | null;

  // ── Triword Address ──
  /** Three-word human-readable address: "observer.observable.context" */
  triword: string;
  /** Formatted triword: "Observer · Observable · Context" */
  triwordFormatted: string;
  /** Triword breakdown into dimensions */
  triwordDimensions: { observer: string; observable: string; context: string } | null;
}

export interface RegistryEntry {
  /** The original JSON-LD source object */
  source: unknown;
  /** The WASM-enriched receipt */
  receipt: EnrichedReceipt;
  /** Timestamp of creation */
  createdAt: number;
  /** How many times this content has been confirmed (re-encoded) */
  confirmations: number;
}

// ── Global Registry ────────────────────────────────────────────────────────

const registry = new Map<string, RegistryEntry>();

/**
 * Enrich a SingleProofResult with WASM ring algebraic data.
 * Every byte passes through the Rust uor-foundation ring engine.
 */
export function enrichWithWasm(proof: SingleProofResult): Omit<EnrichedReceipt, "nquads"> & { nquads: string } {
  const ringByte = proof.hashBytes[0];
  const triword = canonicalToTriword(proof.cid);
  const e = getEngine();

  return {
    cid: proof.cid,
    derivationId: proof.derivationId,
    glyph: proof.uorAddress["u:glyph"],
    ipv6: proof.ipv6Address["u:ipv6"],
    hashHex: proof.hashHex,
    nquads: proof.nquads,

    // Ring signature — every call goes through engine contract → WASM if loaded
    ringByte,
    ringPartition: e.classifyByte(ringByte),
    ringFactors: e.factorize(ringByte),
    ringCriticalIdentity: e.verifyCriticalIdentity(ringByte),
    ringPopcount: e.bytePopcount(ringByte),
    ringBasis: e.byteBasis(ringByte),
    engine: e.engine,
    crateVersion: e.version,

    // Triword address
    triword,
    triwordFormatted: formatTriword(triword),
    triwordDimensions: triwordBreakdown(triword),
  };
}

/**
 * Compute a WASM-anchored receipt for any object and register it.
 * Pipeline: obj → URDNA2015 → SHA-256 → CID + ring signature.
 */
export async function computeAndRegister(source: unknown): Promise<EnrichedReceipt> {
  const proof = await singleProofHash(source);
  const enriched = enrichWithWasm(proof);

  const entry: RegistryEntry = { source, receipt: enriched, createdAt: Date.now(), confirmations: 1 };

  // Index by CID, derivationId, triword, and IPv6 for flexible lookup
  registry.set(enriched.cid, entry);
  registry.set(enriched.derivationId, entry);
  registry.set(enriched.triword, entry);
  registry.set(enriched.ipv6, entry);

  // Persist to database (fire-and-forget, don't block)
  persistToDb(source, enriched).catch((err) =>
    console.warn("[ReceiptRegistry] DB persist failed:", err)
  );

  return enriched;
}

/**
 * Persist an encoded object to the database for cross-session rehydration.
 */
async function persistToDb(source: unknown, receipt: EnrichedReceipt): Promise<void> {
  const { error } = await supabase.from("uor_objects" as any).upsert(
    {
      cid: receipt.cid,
      triword: receipt.triword,
      ipv6: receipt.ipv6,
      derivation_id: receipt.derivationId,
      source: source as any,
      receipt: receipt as any,
    },
    { onConflict: "cid" }
  );
  if (error) throw error;
}

/**
 * Attempt to rehydrate an object from the database by any identity form.
 * Returns the registry entry if found, or undefined.
 */
export async function rehydrateFromDb(key: string): Promise<RegistryEntry | undefined> {
  // Direct registry check first
  const local = lookupReceipt(key);
  if (local) return local;

  const normalized = key.trim().toLowerCase();

  // Query DB by any identity column
  const { data, error } = await supabase
    .from("uor_objects" as any)
    .select("source, receipt, created_at")
    .or(`cid.eq.${key},triword.eq.${normalized},ipv6.eq.${normalized},derivation_id.eq.${key}`)
    .limit(1)
    .maybeSingle();

  if (error || !data) return undefined;

  const source = (data as any).source;
  const receiptData = (data as any).receipt as EnrichedReceipt;
  const createdAt = new Date((data as any).created_at).getTime();

  // Re-register in local memory
  const entry: RegistryEntry = {
    source,
    receipt: receiptData,
    createdAt,
    confirmations: 1,
  };

  registry.set(receiptData.cid, entry);
  registry.set(receiptData.derivationId, entry);
  registry.set(receiptData.triword, entry);
  registry.set(receiptData.ipv6, entry);

  return entry;
}

/**
 * Look up a registry entry by CID, derivation ID, or triword.
 * Accepts any of the three formats.
 */
export function lookupReceipt(key: string): RegistryEntry | undefined {
  // Direct lookup first (covers CID, derivationId, triword, IPv6)
  const direct = registry.get(key);
  if (direct) return direct;

  // Try as triword (normalized lowercase dot-separated)
  const normalized = key.toLowerCase().replace(/\s*[·]\s*/g, ".").replace(/\s+/g, ".").trim();
  if (normalized !== key) {
    const triwordMatch = registry.get(normalized);
    if (triwordMatch) return triwordMatch;
  }

  // IPv6 normalization: lowercase, collapse :: expansions
  const trimmed = key.trim().toLowerCase();
  if (trimmed.startsWith("fd00:0075:6f72")) {
    for (const entry of registry.values()) {
      if (entry.receipt.ipv6.toLowerCase() === trimmed) return entry;
    }
  }

  // Check if it's a valid triword and scan by prefix match
  if (isValidTriword(normalized)) {
    for (const entry of registry.values()) {
      if (entry.receipt.triword === normalized) return entry;
    }
  }

  return undefined;
}

/** Get all registered entries */
export function allEntries(): RegistryEntry[] {
  // Deduplicate (each entry is stored under both CID and derivationId)
  const seen = new Set<string>();
  const result: RegistryEntry[] = [];
  for (const entry of registry.values()) {
    if (!seen.has(entry.receipt.cid)) {
      seen.add(entry.receipt.cid);
      result.push(entry);
    }
  }
  return result;
}

/** Clear the registry */
export function clearRegistry(): void {
  registry.clear();
}

/** Registry size (unique entries) */
export function registrySize(): number {
  return allEntries().length;
}

/**
 * Re-enrich all existing receipts that were created with the TS fallback.
 * Call this after WASM becomes available to upgrade receipts to WASM-anchored.
 */
export async function reEnrichAll(): Promise<number> {
  let upgraded = 0;
  const entries = allEntries();
  for (const entry of entries) {
    if (entry.receipt.engine === "typescript") {
      const enriched = await computeAndRegister(entry.source);
      if (enriched.engine === "wasm") upgraded++;
    }
  }
  return upgraded;
}
