/**
 * Kernel LUT Module — Barrel Export.
 * @module kernel/lut
 */

export {
  ElementWiseView,
  compose,
  composeChain,
  identity,
  negLut,
  bnotLut,
  xorConstLut,
} from "./element-wise-view";

export {
  fromFunction,
  fromOp,
  availableOps,
  sigmoid,
  tanh,
  relu,
  leakyRelu,
  gelu,
  silu,
  softplus,
  elu,
  hardSigmoid,
  hardTanh,
  abs,
  square,
  cube,
  reciprocal,
  exp,
  log,
  sqrt,
  sin,
  cos,
  step,
  softmaxApprox,
  layernormApprox,
  rmsNorm,
  type LutOpName,
} from "./ops";

export {
  fuseChains,
  eliminateIdentities,
  foldConstants,
  optimizeGraph,
  type FusionNode,
} from "./fusion";

export {
  quantizeQ8,
  quantizeQ4,
  generateQ8Booklets,
  generateQ4Booklets,
  lutGemmQ8,
  lutGemmQ4,
  serializeQuantizedMatrix,
  deserializeQuantizedMatrix,
  quantizedMatrixToBlob,
  blobToQuantizedMatrix,
  createGemmComputeNode,
  buildGemmLayer,
  executeGemmLayer,
  type QuantMode,
  type QuantizedMatrix,
  type PartialSumBooklet,
  type GemmBookletSet,
  type LutGemmLayer,
} from "./gemm";

export {
  buildLinearLayer,
  executeLinearLayer,
  buildLayerNormLut,
  buildLayerNormLuts,
  buildRmsNormLut,
  buildSoftmaxLut,
  buildAttentionHead,
  buildFeedForward,
  buildTransformerBlock,
  buildTransformerModel,
  lookupEmbedding,
  quantizeActivation,
  applyLutElementWise,
  forwardPass,
  sampleGreedy,
  sampleTopK,
  type TransformerConfig,
  type TransformerWeights,
  type LayerWeights,
  type LutLinearLayer,
  type LutAttentionHead,
  type LutFeedForward,
  type LutTransformerBlock,
  type LutTransformerModel,
} from "./transformer";
