/**
 * UOR Foundation v2.0.0 — bridge::proof
 *
 * Kernel-produced verification proofs with typed witness data.
 * v0.2.0 additions: InductiveProof, TacticApplication,
 * ProofTerm, ProofContext, ProofObligation, ProofScript.
 *
 * @see foundation/src/bridge/proof.rs
 * @namespace proof/
 */

// ── Core Proof Types ───────────────────────────────────────────────────────

export interface WitnessData {
  witnessId(): string;
  witnessType(): string;
  witnessContent(): string;
  timestamp(): string;
}

/**
 * Proof — abstract base for all proofs.
 */
export interface Proof {
  verified(): boolean;
  quantum(): number;
  witness(): WitnessData;
  provesIdentity(): string | null;
}

/** CoherenceProof — proves system-wide coherence across all modules. */
export interface CoherenceProof extends Proof {
  moduleCount(): number;
  passedCount(): number;
  allCoherent(): boolean;
}

/** CriticalIdentityProof — proves neg(bnot(x)) = succ(x) for all x. */
export interface CriticalIdentityProof extends Proof {
  provesIdentity(): "neg(bnot(x)) = succ(x)";
  testedCount(): number;
  passedCount(): number;
  failedCount(): number;
  holds(): boolean;
}

// ══════════════════════════════════════════════════════════════════════════
// v0.2.0 ADDITIONS
// ══════════════════════════════════════════════════════════════════════════

/**
 * InductiveProof — a proof by structural or well-founded induction.
 * Anchored to kernel::recursion's DescentMeasure for termination.
 *
 * @see spec/src/namespaces/proof.rs — InductiveProof
 */
export interface InductiveProof extends Proof {
  /** Base case witness. */
  baseCase(): WitnessData;
  /** Inductive step witness. */
  inductiveStep(): WitnessData;
  /** Descent measure used for well-foundedness. */
  descentMeasure(): string;
  /** Maximum induction depth reached. */
  maxDepth(): number;
}

/**
 * TacticApplication — a single step in a tactic-style proof.
 * Records the tactic name, arguments, and resulting proof state.
 *
 * @see spec/src/namespaces/proof.rs — TacticApplication
 */
export interface TacticApplication {
  /** Tactic name (e.g., "intro", "apply", "rewrite", "ring"). */
  tacticName(): string;
  /** Arguments to the tactic. */
  arguments(): string[];
  /** Goals remaining after applying this tactic. */
  remainingGoals(): number;
  /** Whether this tactic closed a goal. */
  closedGoal(): boolean;
}

/**
 * ProofTerm — a term in the proof language (Curry-Howard correspondence).
 * Proof terms are programs that inhabit proposition types.
 *
 * @see spec/src/namespaces/proof.rs — ProofTerm
 */
export interface ProofTerm {
  /** Term kind (e.g., "Lambda", "Apply", "Refl", "Subst"). */
  kind(): string;
  /** Canonical string representation. */
  canonical(): string;
  /** The proposition (type) this term proves. */
  propositionType(): string;
  /** Sub-terms. */
  children(): ProofTerm[];
}

/**
 * ProofContext — the current proof state: hypotheses + goals.
 *
 * @see spec/src/namespaces/proof.rs — ProofContext
 */
export interface ProofContext {
  /** Named hypotheses. */
  hypotheses(): Array<{ name: string; proposition: string }>;
  /** Current goals (propositions to prove). */
  goals(): string[];
  /** Whether the proof is complete (no goals remain). */
  isComplete(): boolean;
}

/**
 * ProofObligation — a proof obligation generated by the type checker
 * or enforcement module that must be discharged.
 *
 * @see spec/src/namespaces/proof.rs — ProofObligation
 */
export interface ProofObligation {
  /** Obligation identifier. */
  obligationId(): string;
  /** The proposition to prove. */
  proposition(): string;
  /** Source of the obligation (e.g., "refinement_type", "assertion", "grounding"). */
  source(): string;
  /** Whether the obligation has been discharged. */
  discharged(): boolean;
  /** Proof term (if discharged). */
  proofTerm(): ProofTerm | null;
}

/**
 * ProofScript — a complete proof as a sequence of tactic applications.
 *
 * @see spec/src/namespaces/proof.rs — ProofScript
 */
export interface ProofScript {
  /** Script identifier. */
  scriptId(): string;
  /** Ordered tactic applications. */
  tactics(): TacticApplication[];
  /** Initial proof context. */
  initialContext(): ProofContext;
  /** Final proof context (should be complete). */
  finalContext(): ProofContext;
  /** Whether the script constitutes a complete proof. */
  isComplete(): boolean;
}
