/**
 * UOR Entity Resolver. DihedralFactorizationResolver
 *
 * Resolves natural-language entity descriptions to canonical IDs
 * using dihedral factorization of UTF-8 bytes in Z/256Z.
 *
 * Algorithm:
 *   1. UTF-8 encode entity → bytes
 *   2. For each byte: classify (partition class) + factorize in D_{2^8}
 *   3. Compute canonicalId = singleProofHash({ entity, factorization })
 *   4. Search Q0 graph for closest match by Hamming proximity
 *   5. Grade: exact=A, graph-certified=B, proximity=C, none=D
 *
 * @see spec/src/namespaces/resolver.rs. DihedralFactorizationResolver
 */

import { singleProofHash } from "@/modules/identity/uns/core/identity";
import type { UnsGraph } from "@/modules/data/knowledge-graph/uns-graph";

// ── Types ───────────────────────────────────────────────────────────────────

export type EpistemicGrade = "A" | "B" | "C" | "D";

export interface DihedralFactor {
  byte: number;
  partitionClass: string;
  factor: string;
}

export interface EntityResolution {
  "@type": "resolver:Resolution";
  "resolver:input": string;
  "resolver:canonicalId": string;
  "resolver:strategy": "DihedralFactorizationResolver";
  "resolver:factorization": DihedralFactor[];
  "resolver:partitionDensity": number;
  "resolver:confidence": number;
  epistemic_grade: EpistemicGrade;
  "derivation:derivationId": string;
}

// ── Partition classification ────────────────────────────────────────────────

function classifyByteQ0(b: number): string {
  if (b === 0 || b === 128) return "partition:ExteriorSet";
  if (b === 1 || b === 255) return "partition:UnitSet";
  if (b % 2 === 1) return "partition:IrreducibleSet";
  return "partition:ReducibleSet";
}

// ── Dihedral factorization ──────────────────────────────────────────────────

/**
 * Factorize a byte in the dihedral group D_{2^8}.
 *
 * The dihedral group is generated by rotation r and reflection s:
 *   - r(x) = (x + 1) mod 256  (successor = rotation)
 *   - s(x) = x XOR 0xFF       (bnot = reflection)
 *
 * Every element can be expressed as r^k or s·r^k.
 * For a given byte b:
 *   - If b is odd (irreducible/unit): direct rotation r^b
 *   - If b is even (reducible/exterior): decompose into 2^p × m
 */
function dihedralFactorize(b: number): string {
  if (b === 0) return "r^0 (identity)";
  if (b === 1) return "r^1 (generator)";
  if (b === 255) return "s (reflection)";
  if (b === 128) return "r^128 (half-turn)";

  // Factor out powers of 2
  let val = b;
  let twos = 0;
  while (val > 0 && val % 2 === 0) {
    twos++;
    val = val >> 1;
  }

  if (twos === 0) {
    return `r^${b}`;
  }
  if (val === 1) {
    return `2^${twos}`;
  }
  return `2^${twos} × ${val}`;
}

// ── Hamming distance for matching ───────────────────────────────────────────

function popcount8(b: number): number {
  let n = b & 0xff;
  n = n - ((n >> 1) & 0x55);
  n = (n & 0x33) + ((n >> 2) & 0x33);
  return (n + (n >> 4)) & 0x0f;
}

function hexToBytes(hex: string): Uint8Array {
  const clean = hex.includes(":") ? hex.split(":").pop()! : hex;
  const bytes = new Uint8Array(clean.length / 2);
  for (let i = 0; i < bytes.length; i++) {
    bytes[i] = parseInt(clean.substring(i * 2, i * 2 + 2), 16);
  }
  return bytes;
}

function hammingDistHex(a: string, b: string): number {
  const ba = hexToBytes(a);
  const bb = hexToBytes(b);
  let dist = 0;
  for (let i = 0; i < Math.min(ba.length, bb.length); i++) {
    dist += popcount8(ba[i] ^ bb[i]);
  }
  return dist;
}

// ── Entity Resolution ───────────────────────────────────────────────────────

/**
 * Resolve a natural-language entity description to a canonical ID
 * using DihedralFactorizationResolver.
 */
export async function resolveEntity(
  entity: string,
  context: string | undefined,
  graph: UnsGraph
): Promise<EntityResolution> {
  // 1. UTF-8 encode
  const bytes = new TextEncoder().encode(entity);

  // 2. Factorize each byte
  const factorization: DihedralFactor[] = [];
  let irreducibleCount = 0;
  for (const b of bytes) {
    const partitionClass = classifyByteQ0(b);
    if (partitionClass === "partition:IrreducibleSet") irreducibleCount++;
    factorization.push({
      byte: b,
      partitionClass,
      factor: dihedralFactorize(b),
    });
  }

  // 3. Compute canonical ID of the entity+factorization
  const entityObj: Record<string, unknown> = {
    "@type": "resolver:Resolution",
    "resolver:input": entity,
    "resolver:strategy": "DihedralFactorizationResolver",
    "resolver:factorization": factorization.map((f) => ({
      byte: f.byte,
      class: f.partitionClass,
    })),
  };
  if (context) entityObj["resolver:context"] = context;

  const identity = await singleProofHash(entityObj);
  const canonicalId = identity["u:canonicalId"];

  // 4. Partition density = irreducibleCount / totalBytes
  const density =
    bytes.length > 0
      ? Math.round((irreducibleCount / bytes.length) * 10000) / 10000
      : 0;

  // 5. Search graph for closest match by Hamming proximity
  let bestGrade: EpistemicGrade = "D";
  let confidence = 0;

  // Check for exact match in graph
  const allQuads = graph.allQuads();
  const subjectSet = new Set<string>();
  for (const q of allQuads) {
    subjectSet.add(q.subject);
  }

  // Check if our canonical ID matches any graph subject
  if (subjectSet.has(canonicalId)) {
    bestGrade = "A";
    confidence = 1.0;
  } else {
    // Find closest by Hamming to datum IRIs
    const canonicalHex = canonicalId.split(":").pop() ?? "";
    let minDist = Infinity;

    // Check datums for proximity
    for (let n = 0; n < 256; n++) {
      const datumIri = `https://uor.foundation/datum/q0/${n}`;
      if (subjectSet.has(datumIri)) {
        // Compute hash of datum for comparison
        const datumIdentity = await singleProofHash({
          "@type": "schema:Datum",
          "schema:value": n,
        });
        const datumHex = datumIdentity["u:canonicalId"].split(":").pop() ?? "";
        const dist = hammingDistHex(canonicalHex, datumHex);
        if (dist < minDist) minDist = dist;
      }
    }

    // Assign grade based on proximity
    if (minDist <= 32) {
      bestGrade = "B";
      confidence = Math.round((1 - minDist / 256) * 10000) / 10000;
    } else if (minDist <= 128) {
      bestGrade = "C";
      confidence = Math.round((1 - minDist / 256) * 10000) / 10000;
    } else {
      bestGrade = "D";
      confidence = Math.round(Math.max(0, 1 - minDist / 256) * 10000) / 10000;
    }
  }

  return {
    "@type": "resolver:Resolution",
    "resolver:input": entity,
    "resolver:canonicalId": canonicalId,
    "resolver:strategy": "DihedralFactorizationResolver",
    "resolver:factorization": factorization,
    "resolver:partitionDensity": density,
    "resolver:confidence": confidence,
    epistemic_grade: bestGrade,
    "derivation:derivationId": canonicalId,
  };
}
