/**
 * UOR v2.0.0. Geometric Reasoning Primitives
 *
 * Formalizes the three reasoning modes as first-class operations on the ring:
 *
 *   Vertical   (Deductive) . constraint propagation → pinned fibers
 *   Horizontal (Inductive) . pattern matching → Hamming similarity
 *   Diagonal   (Abductive) . curvature between deductive & inductive results
 *
 * The canonical mapping:
 *   MetricAxis → ReasoningMode
 *   Vertical   → deductive
 *   Horizontal → inductive
 *   Diagonal   → abductive
 *
 * Pure functions. No classes. No side effects.
 *
 * @module ring-core/reasoning
 * @see plan.md Phase 2
 */

import type { MetricAxis } from "@/types/uor-foundation/enums";
import type { FiberBudget } from "@/types/uor-foundation/bridge/partition";
import { applyConstraint } from "./constraint";
import { resolution } from "./fiber-budget";

// ── Core Types ─────────────────────────────────────────────────────────────

export type ReasoningMode = "deductive" | "inductive" | "abductive";

/** Canonical mapping: MetricAxis → ReasoningMode */
export const AXIS_TO_REASONING: Record<MetricAxis, ReasoningMode> = {
  Vertical:   "deductive",
  Horizontal: "inductive",
  Diagonal:   "abductive",
};

/** Inverse mapping: ReasoningMode → MetricAxis */
export const REASONING_TO_AXIS: Record<ReasoningMode, MetricAxis> = {
  deductive: "Vertical",
  inductive: "Horizontal",
  abductive: "Diagonal",
};

// ── Reasoning Step Results ─────────────────────────────────────────────────

/** Result of a deductive step: constraint → pinned fibers. */
export interface DeductiveResult {
  readonly mode: "deductive";
  readonly axis: "Vertical";
  /** The constraint that was applied. */
  readonly constraintId: string;
  /** Fiber budget after applying the constraint. */
  readonly budget: FiberBudget;
  /** Resolution ratio [0, 1]. depth of the deduction. */
  readonly depth: number;
  /** Number of fibers pinned in this step. */
  readonly fibersPinned: number;
}

/** Result of an inductive step: observation → similarity score. */
export interface InductiveResult {
  readonly mode: "inductive";
  readonly axis: "Horizontal";
  /** The observed value (e.g., from neural inference). */
  readonly observation: number;
  /** The reference value (known ring element). */
  readonly reference: number;
  /** Hamming distance between observation and reference. */
  readonly hammingDistance: number;
  /** Confidence = 1 - (hammingDistance / totalBits). Closer = more confident. */
  readonly confidence: number;
  /** Total bits compared. */
  readonly totalBits: number;
}

/** Result of an abductive step: curvature between D and I. */
export interface AbductiveResult {
  readonly mode: "abductive";
  readonly axis: "Diagonal";
  /** Curvature: measure of disagreement between deductive and inductive. */
  readonly curvatureValue: number;
  /** Normalized curvature [0, 1]. */
  readonly normalizedCurvature: number;
  /** Whether curvature exceeds catastrophe threshold (phase transition). */
  readonly isCatastrophe: boolean;
  /** Holonomy: non-zero means reasoning loop doesn't close (inconsistency). */
  readonly holonomyValue: number;
  /** Generated hypothesis if curvature is non-zero. */
  readonly hypothesis: AbductiveHypothesis | null;
}

/** A hypothesis generated by non-zero abductive curvature. */
export interface AbductiveHypothesis {
  /** Description of the gap between deduction and induction. */
  readonly description: string;
  /** Suggested constraint to close the gap. */
  readonly suggestedConstraintType: string;
  /** Expected number of fibers this hypothesis would resolve. */
  readonly expectedResolutions: number;
  /** Confidence in this hypothesis [0, 1]. */
  readonly confidence: number;
}

/** A complete reasoning cycle: D → I → A. */
export interface ReasoningCycle {
  readonly cycleIndex: number;
  readonly deductive: DeductiveResult;
  readonly inductive: InductiveResult;
  readonly abductive: AbductiveResult;
  /** Whether the cycle converged (curvature ≈ 0). */
  readonly converged: boolean;
}

// ── Constants ──────────────────────────────────────────────────────────────

/**
 * Catastrophe threshold derived from ring geometry.
 * 4/256 = 0.015625 at Q0. Curvature above this triggers phase transition.
 */
export const CATASTROPHE_THRESHOLD_Q0 = 4 / 256;

/** Convergence epsilon: curvature below this is considered zero. */
export const CONVERGENCE_EPSILON = 1e-10;

// ── Deductive Step (Vertical Axis) ─────────────────────────────────────────

/**
 * Execute a deductive step: apply a constraint to a fiber budget.
 *
 * Deduction = top-down reasoning from axiom/premise to conclusion.
 * Each constraint pins fibers (resolves bits), narrowing the search space.
 * The soundness guarantee: every pinned fiber carries its constraintId.
 */
export function deductiveStep(
  budget: FiberBudget,
  constraint: {
    constraintId: string;
    axis: MetricAxis;
    crossingCost: number;
    satisfies: (value: bigint) => boolean;
  },
  pinsExpected: number,
): DeductiveResult {
  const pinnedBefore = budget.pinnedCount;
  const newBudget = applyConstraint(budget, constraint, pinsExpected);
  const fibersPinned = newBudget.pinnedCount - pinnedBefore;

  return {
    mode: "deductive",
    axis: "Vertical",
    constraintId: constraint.constraintId,
    budget: newBudget,
    depth: resolution(newBudget),
    fibersPinned,
  };
}

// ── Inductive Step (Horizontal Axis) ───────────────────────────────────────

/**
 * Execute an inductive step: measure similarity between observation and reference.
 *
 * Induction = bottom-up reasoning from observation to pattern.
 * Uses Hamming distance to measure how close an observation is to a known element.
 * Confidence = inverse of normalized Hamming distance.
 */
export function inductiveStep(
  observation: number,
  reference: number,
  quantum = 0,
): InductiveResult {
  const totalBits = 8 * (quantum + 1);

  // Compute Hamming distance
  let xored = observation ^ reference;
  let distance = 0;
  while (xored > 0) {
    distance += xored & 1;
    xored >>>= 1;
  }

  const confidence = 1 - distance / totalBits;

  return {
    mode: "inductive",
    axis: "Horizontal",
    observation,
    reference,
    hammingDistance: distance,
    confidence,
    totalBits,
  };
}

/**
 * Find the nearest ring element to an observation by Hamming distance.
 * Returns the inductive result for the closest match.
 */
export function inductiveNearest(
  observation: number,
  candidates: number[],
  quantum = 0,
): InductiveResult {
  if (candidates.length === 0) {
    throw new Error("inductiveNearest requires at least one candidate");
  }

  let best = inductiveStep(observation, candidates[0], quantum);
  for (let i = 1; i < candidates.length; i++) {
    const result = inductiveStep(observation, candidates[i], quantum);
    if (result.hammingDistance < best.hammingDistance) {
      best = result;
    }
  }
  return best;
}

// ── Abductive Step (Diagonal Axis) ─────────────────────────────────────────

/**
 * Compute abductive curvature between a deductive prediction and an inductive observation.
 *
 * Abduction = inference to the best explanation.
 * Curvature measures the gap between what the symbolic system predicts (deduction)
 * and what the neural system observes (induction).
 *
 * - Zero curvature → agreement (no hypothesis needed)
 * - Non-zero curvature → generates a hypothesis to explain the gap
 * - Curvature > catastropheThreshold → phase transition (paradigm shift)
 *
 * Holonomy measures whether the reasoning loop closes:
 * - Zero holonomy → consistent reasoning
 * - Non-zero holonomy → inconsistency detected (hallucination signal)
 */
export function abductiveCurvature(
  deductive: DeductiveResult,
  inductive: InductiveResult,
  quantum = 0,
): AbductiveResult {
  const totalBits = 8 * (quantum + 1);
  const threshold = 4 / (1 << totalBits); // Ring-derived threshold

  // Curvature = how much the inductive observation deviates from deductive expectation
  // Normalized by total bits so it's comparable across quantum levels
  const curvatureValue = inductive.hammingDistance;
  const normalizedCurvature = curvatureValue / totalBits;

  const isCatastrophe = normalizedCurvature > threshold;

  // Holonomy: if we went D → I → back, does the loop close?
  // Measured as |depth - confidence|. if deductive depth matches inductive confidence,
  // the loop closes (holonomy = 0).
  const holonomyValue = Math.abs(deductive.depth - inductive.confidence);

  // Generate hypothesis if curvature is non-zero
  let hypothesis: AbductiveHypothesis | null = null;
  if (curvatureValue > 0) {
    const gapFibers = Math.max(1, Math.ceil(
      (1 - inductive.confidence) * deductive.budget.totalFibers - deductive.budget.pinnedCount
    ));

    hypothesis = {
      description: isCatastrophe
        ? `Phase transition: ${curvatureValue}-bit disagreement exceeds catastrophe threshold. Paradigm shift needed.`
        : `${curvatureValue}-bit gap between symbolic prediction and neural observation. Refinement constraint suggested.`,
      suggestedConstraintType: isCatastrophe ? "CompositeConstraint" : "ResidueConstraint",
      expectedResolutions: Math.max(1, gapFibers),
      confidence: inductive.confidence * deductive.depth,
    };
  }

  return {
    mode: "abductive",
    axis: "Diagonal",
    curvatureValue,
    normalizedCurvature,
    isCatastrophe,
    holonomyValue,
    hypothesis,
  };
}

// ── Reasoning Cycle ────────────────────────────────────────────────────────

/**
 * Execute a single D → I → A reasoning cycle.
 *
 * 1. Deductive: apply constraint to pin fibers (narrow hypothesis space)
 * 2. Inductive: compare observation to reference (measure similarity)
 * 3. Abductive: measure curvature between 1 and 2 (generate hypothesis if gap)
 *
 * Returns the full cycle with convergence status.
 */
export function reasoningCycle(
  budget: FiberBudget,
  constraint: {
    constraintId: string;
    axis: MetricAxis;
    crossingCost: number;
    satisfies: (value: bigint) => boolean;
  },
  pinsExpected: number,
  observation: number,
  reference: number,
  quantum = 0,
  cycleIndex = 0,
): ReasoningCycle {
  const d = deductiveStep(budget, constraint, pinsExpected);
  const i = inductiveStep(observation, reference, quantum);
  const a = abductiveCurvature(d, i, quantum);

  return {
    cycleIndex,
    deductive: d,
    inductive: i,
    abductive: a,
    converged: a.normalizedCurvature < CONVERGENCE_EPSILON,
  };
}

/**
 * Run iterative D → I → A cycles until convergence or max iterations.
 * Each cycle's abductive hypothesis feeds into the next deductive step.
 */
export function reasoningLoop(
  quantum: number,
  steps: Array<{
    constraint: {
      constraintId: string;
      axis: MetricAxis;
      crossingCost: number;
      satisfies: (value: bigint) => boolean;
    };
    pinsExpected: number;
    observation: number;
    reference: number;
  }>,
  initialBudget: FiberBudget,
  maxIterations?: number,
): ReasoningCycle[] {
  const max = maxIterations ?? steps.length;
  const cycles: ReasoningCycle[] = [];
  let currentBudget = initialBudget;

  for (let i = 0; i < Math.min(max, steps.length); i++) {
    const step = steps[i];
    const cycle = reasoningCycle(
      currentBudget,
      step.constraint,
      step.pinsExpected,
      step.observation,
      step.reference,
      quantum,
      i,
    );
    cycles.push(cycle);

    // Feed deductive result forward
    currentBudget = cycle.deductive.budget;

    // If converged, stop
    if (cycle.converged) break;
  }

  return cycles;
}
