/**
 * EpistemicBadge. Inline proof annotation for neuro-symbolic responses.
 *
 * By default, the response shows clean readable text. A toggle at the
 * bottom lets users reveal the full chain-of-thought with epistemic
 * grade badges and proof metadata.
 *
 * When the overall trust score is low (Grade C or D), a prominent but
 * warm advisory banner appears, explaining WHY trust is low and HOW
 * to improve it. making the system transparent and empowering.
 */

import { useState } from "react";
import ReactMarkdown from "react-markdown";
import type { AnnotatedClaim, EpistemicGrade } from "@/modules/kernel/ring-core/neuro-symbolic";
import {
  ChevronDown, ChevronUp, Shield, ShieldAlert, AlertTriangle,
  Lightbulb, ArrowRight, CheckCircle2, Info, ExternalLink,
} from "lucide-react";

// ── Grade Styling (warm tones matching Hologram palette) ──────────────────

const GRADE_STYLES: Record<EpistemicGrade, { color: string; bg: string; label: string; icon: string; description: string }> = {
  A: {
    color: "hsl(160, 45%, 55%)",
    bg: "hsla(160, 45%, 55%, 0.1)",
    label: "Proven",
    icon: "◆",
    description: "Backed by algebraic proof with a full derivation chain.",
  },
  B: {
    color: "hsl(200, 45%, 60%)",
    bg: "hsla(200, 45%, 60%, 0.1)",
    label: "Verified",
    icon: "◇",
    description: "Cross-referenced against verified knowledge sources.",
  },
  C: {
    color: "hsl(38, 50%, 55%)",
    bg: "hsla(38, 50%, 55%, 0.1)",
    label: "Plausible",
    icon: "○",
    description: "Logically consistent but not independently verified.",
  },
  D: {
    color: "hsl(30, 10%, 55%)",
    bg: "hsla(30, 10%, 55%, 0.08)",
    label: "Unverified",
    icon: "·",
    description: "Generated by AI without supporting evidence. Treat as a starting point.",
  },
};

const P = {
  font: "'DM Sans', sans-serif",
  fontDisplay: "'Playfair Display', serif",
  text: "hsl(38, 20%, 85%)",
  textMuted: "hsl(30, 10%, 60%)",
  textDim: "hsl(30, 10%, 50%)",
  border: "hsla(38, 30%, 30%, 0.2)",
  goldLight: "hsl(38, 60%, 60%)",
  goldMuted: "hsl(38, 40%, 45%)",
} as const;

// ── Helpers ────────────────────────────────────────────────────────────────

/** Turn a source string into a clickable search URL when it references a real source. */
function getSourceUrl(source: string): string | null {
  if (!source) return null;
  const s = source.trim();
  // Already a URL
  if (/^https?:\/\//i.test(s)) return s;
  // Internal/generated sources. not linkable
  if (/^(scaffold|llm-generated|ring-core|internal|cache|local)/i.test(s)) return null;
  if (s.length < 8) return null;
  // Real-sounding sources → Google Scholar search
  return `https://scholar.google.com/scholar?q=${encodeURIComponent(s)}`;
}

/** Render a source string, clickable when it references a real source. */
function SourceLink({ source, color }: { source: string; color?: string }) {
  const url = getSourceUrl(source);
  if (!url) {
    return <span style={{ color: color ?? P.textMuted }}>{source}</span>;
  }
  return (
    <a
      href={url}
      target="_blank"
      rel="noopener noreferrer"
      className="inline-flex items-center gap-1 transition-opacity hover:opacity-80"
      style={{
        color: color ?? P.goldMuted,
        textDecoration: "none",
        borderBottom: `1px solid hsla(38, 30%, 50%, 0.2)`,
      }}
      title={`Search for: ${source}`}
    >
      {source}
      <ExternalLink className="w-2.5 h-2.5 inline-block flex-shrink-0" style={{ opacity: 0.6 }} />
    </a>
  );
}

function isLowTrust(grade: EpistemicGrade): boolean {
  return grade === "C" || grade === "D";
}

/** Analyze claims to determine WHY trust is low and WHAT can improve it. */
function analyzeLowTrust(
  claims: AnnotatedClaim[],
  grade: EpistemicGrade,
  converged: boolean,
  curvature: number,
): { reasons: string[]; steps: string[] } {
  const reasons: string[] = [];
  const steps: string[] = [];

  const dCount = claims.filter((c) => c.grade === "D").length;
  const cCount = claims.filter((c) => c.grade === "C").length;
  const total = claims.length;
  const unverifiedPct = total > 0 ? Math.round(((dCount + cCount) / total) * 100) : 0;

  // ── Reasons ────────────────────────────
  if (dCount > 0 && dCount === total) {
    reasons.push("None of the claims in this response could be verified against known sources.");
  } else if (dCount > 0) {
    reasons.push(`${dCount} of ${total} claims are unverified. generated without supporting evidence.`);
  }
  if (cCount > 0 && dCount === 0) {
    reasons.push(`${cCount} of ${total} claims are plausible but haven't been independently confirmed.`);
  }
  if (!converged) {
    reasons.push("The reasoning engine didn't fully converge. the answer may still be shifting.");
  }
  if (curvature > 0.5) {
    reasons.push("High divergence detected between the AI's output and the symbolic scaffold.");
  }
  if (reasons.length === 0) {
    reasons.push("This topic falls outside well-verified knowledge domains.");
  }

  // ── Steps to improve ──────────────────
  if (dCount > 0) {
    steps.push("Ask a more specific question to help Lumen find verified sources.");
  }
  if (unverifiedPct > 60) {
    steps.push("Try breaking the question into smaller, more focused parts.");
  }
  if (!converged) {
    steps.push("Rephrase or add context so the reasoning engine can converge.");
  }
  steps.push("Use the chain of thought below to inspect each claim's source.");
  if (grade === "D") {
    steps.push("Treat this response as a hypothesis. verify key points independently.");
  }

  return { reasons, steps };
}

// ── Components ─────────────────────────────────────────────────────────────

function GradeBadge({ grade, onClick }: { grade: EpistemicGrade; onClick?: () => void }) {
  const style = GRADE_STYLES[grade];
  return (
    <button
      onClick={onClick}
      className="inline-flex items-center gap-1 px-1.5 py-0.5 rounded-md text-[10px] font-medium cursor-pointer transition-all duration-200 hover:brightness-110"
      style={{
        background: style.bg,
        color: style.color,
        border: `1px solid ${style.color}22`,
        fontFamily: P.font,
        letterSpacing: "0.05em",
      }}
      title={`Grade ${grade}: ${style.label}`}
    >
      <span style={{ fontSize: "8px" }}>{style.icon}</span>
      {grade}
    </button>
  );
}

function ClaimTooltip({ claim, onClose }: { claim: AnnotatedClaim; onClose: () => void }) {
  const style = GRADE_STYLES[claim.grade];
  return (
    <div
      className="absolute z-50 bottom-full left-0 mb-2 w-72 rounded-xl shadow-2xl animate-in fade-in slide-in-from-bottom-2 duration-200"
      style={{
        background: "hsl(30, 8%, 16%)",
        border: `1px solid ${P.border}`,
        fontFamily: P.font,
      }}
      onClick={(e) => e.stopPropagation()}
    >
      <div
        className="flex items-center justify-between px-3.5 py-2.5"
        style={{ borderBottom: `1px solid ${P.border}` }}
      >
        <div className="flex items-center gap-2">
          <span className="text-[10px]" style={{ color: style.color }}>{style.icon}</span>
          <span className="text-xs font-medium" style={{ color: style.color }}>
            Grade {claim.grade}. {style.label}
          </span>
        </div>
        <button
          onClick={onClose}
          className="text-xs transition-colors hover:opacity-80"
          style={{ color: P.textDim }}
        >
          ✕
        </button>
      </div>
      <div className="px-3.5 py-2.5 space-y-1.5">
        <div className="text-[11px]" style={{ color: P.textMuted }}>
          <span style={{ color: P.text }}>Source: </span>
          <SourceLink source={claim.source} />
        </div>
        <div className="text-[11px]" style={{ color: P.textMuted }}>
          <span style={{ color: P.text }}>Curvature:</span> {(claim.curvature * 100).toFixed(1)}%
        </div>
        {claim.stepIndex !== null && (
          <div className="text-[11px]" style={{ color: P.textMuted }}>
            <span style={{ color: P.text }}>Proof step:</span> #{claim.stepIndex}
          </div>
        )}
      </div>
    </div>
  );
}

// ── Low Trust Advisory ─────────────────────────────────────────────────────

function LowTrustAdvisory({
  grade,
  claims,
  converged,
  curvature,
}: {
  grade: EpistemicGrade;
  claims: AnnotatedClaim[];
  converged: boolean;
  curvature: number;
}) {
  const [expanded, setExpanded] = useState(false);
  const style = GRADE_STYLES[grade];
  const { reasons, steps } = analyzeLowTrust(claims, grade, converged, curvature);
  const groundedCount = claims.filter((c) => c.grade <= "B").length;
  const total = claims.length;

  const isDGrade = grade === "D";
  const accentColor = isDGrade ? "hsl(15, 50%, 55%)" : "hsl(38, 50%, 55%)";
  const accentBg = isDGrade ? "hsla(15, 50%, 55%, 0.08)" : "hsla(38, 50%, 55%, 0.08)";
  const accentBorder = isDGrade ? "hsla(15, 50%, 55%, 0.2)" : "hsla(38, 50%, 55%, 0.2)";

  return (
    <div
      className="rounded-xl overflow-hidden transition-all duration-300 animate-in fade-in slide-in-from-top-1"
      style={{
        background: accentBg,
        border: `1px solid ${accentBorder}`,
        fontFamily: P.font,
      }}
    >
      {/* Summary bar. always visible */}
      <button
        onClick={() => setExpanded((v) => !v)}
        className="w-full flex items-center gap-3 px-4 py-3 text-left transition-colors duration-200"
        style={{ background: "transparent" }}
        onMouseEnter={(e) => {
          e.currentTarget.style.background = isDGrade
            ? "hsla(15, 50%, 55%, 0.05)"
            : "hsla(38, 50%, 55%, 0.05)";
        }}
        onMouseLeave={(e) => {
          e.currentTarget.style.background = "transparent";
        }}
      >
        {/* Trust indicator */}
        <div
          className="flex items-center justify-center w-8 h-8 rounded-lg shrink-0"
          style={{ background: accentBg, border: `1px solid ${accentBorder}` }}
        >
          {isDGrade ? (
            <ShieldAlert className="w-4 h-4" style={{ color: accentColor }} />
          ) : (
            <AlertTriangle className="w-4 h-4" style={{ color: accentColor }} />
          )}
        </div>

        <div className="min-w-0 flex-1">
          <div className="flex items-center gap-2">
            <span
              className="text-[13px] font-medium"
              style={{ color: accentColor }}
            >
              {isDGrade ? "Low confidence" : "Moderate confidence"}
            </span>
            <span
              className="text-[10px] px-1.5 py-0.5 rounded font-medium"
              style={{
                background: style.bg,
                color: style.color,
                letterSpacing: "0.05em",
              }}
            >
              {style.icon} {style.label}
            </span>
          </div>
          <span
            className="text-[11px] block mt-0.5"
            style={{ color: P.textMuted }}
          >
            {groundedCount} of {total} claims verified
            {isDGrade
              ? ". please verify this information independently"
              : ". some claims need further verification"}
          </span>
        </div>

        <ChevronDown
          className="w-4 h-4 shrink-0 transition-transform duration-200"
          style={{
            color: P.textDim,
            transform: expanded ? "rotate(180deg)" : "rotate(0deg)",
          }}
        />
      </button>

      {/* Expanded details */}
      {expanded && (
        <div
          className="px-4 pb-4 space-y-4 animate-in fade-in slide-in-from-top-1 duration-200"
          style={{ borderTop: `1px solid ${accentBorder}` }}
        >
          {/* Why is trust low? */}
          <div className="pt-3">
            <div className="flex items-center gap-2 mb-2">
              <Info className="w-3.5 h-3.5" style={{ color: accentColor }} />
              <span
                className="text-[12px] font-medium tracking-wide"
                style={{ color: accentColor }}
              >
                Why is the trust score low?
              </span>
            </div>
            <ul className="space-y-1.5 pl-1">
              {reasons.map((reason, i) => (
                <li
                  key={i}
                  className="flex items-start gap-2 text-[12px] leading-relaxed"
                  style={{ color: P.textMuted }}
                >
                  <span
                    className="mt-1.5 w-1 h-1 rounded-full shrink-0"
                    style={{ background: accentColor }}
                  />
                  {reason}
                </li>
              ))}
            </ul>
          </div>

          {/* How to improve */}
          <div>
            <div className="flex items-center gap-2 mb-2">
              <Lightbulb className="w-3.5 h-3.5" style={{ color: P.goldLight }} />
              <span
                className="text-[12px] font-medium tracking-wide"
                style={{ color: P.goldLight }}
              >
                How to get a higher trust score
              </span>
            </div>
            <ul className="space-y-2 pl-1">
              {steps.map((step, i) => (
                <li
                  key={i}
                  className="flex items-start gap-2.5 text-[12px] leading-relaxed"
                  style={{ color: "hsl(30, 12%, 75%)" }}
                >
                  <div
                    className="flex items-center justify-center w-4 h-4 rounded shrink-0 mt-0.5"
                    style={{
                      background: "hsla(38, 40%, 50%, 0.1)",
                      border: "1px solid hsla(38, 40%, 50%, 0.15)",
                    }}
                  >
                    <span
                      className="text-[9px] font-bold"
                      style={{ color: P.goldLight }}
                    >
                      {i + 1}
                    </span>
                  </div>
                  {step}
                </li>
              ))}
            </ul>
          </div>

          {/* Grade scale reference */}
          <div
            className="flex items-center gap-3 pt-2 flex-wrap"
            style={{ borderTop: `1px solid ${accentBorder}` }}
          >
            {(["A", "B", "C", "D"] as EpistemicGrade[]).map((g) => {
              const s = GRADE_STYLES[g];
              const isActive = g === grade;
              return (
                <div
                  key={g}
                  className="flex items-center gap-1.5 px-2 py-1 rounded-lg text-[10px]"
                  style={{
                    background: isActive ? s.bg : "transparent",
                    border: isActive ? `1px solid ${s.color}33` : "1px solid transparent",
                    color: isActive ? s.color : P.textDim,
                    fontWeight: isActive ? 600 : 400,
                    opacity: isActive ? 1 : 0.6,
                  }}
                >
                  <span style={{ fontSize: "7px" }}>{s.icon}</span>
                  <span>{s.label}</span>
                </div>
              );
            })}
          </div>
        </div>
      )}
    </div>
  );
}

// ── Annotated Claim ────────────────────────────────────────────────────────

export function AnnotatedClaimView({ claim, delay = 0 }: { claim: AnnotatedClaim; delay?: number }) {
  const [showTooltip, setShowTooltip] = useState(false);

  return (
    <span
      className="relative inline animate-in fade-in slide-in-from-bottom-1"
      style={{ animationDelay: `${delay}ms`, animationDuration: "500ms", animationFillMode: "both" }}
    >
      <ReactMarkdown
        components={{
          p: ({ children }) => <span>{children} </span>,
          strong: ({ children }) => (
            <strong style={{ color: P.text, fontWeight: 600 }}>{children}</strong>
          ),
          em: ({ children }) => (
            <em style={{ color: P.goldLight, fontStyle: "italic" }}>{children}</em>
          ),
          code: ({ children }) => (
            <code
              style={{
                background: "hsla(38, 30%, 30%, 0.2)",
                padding: "1px 5px",
                borderRadius: "4px",
                fontSize: "0.9em",
                color: P.goldLight,
              }}
            >
              {children}
            </code>
          ),
          ul: ({ children }) => (
            <ul style={{ listStyle: "none", paddingLeft: "0.5em", margin: "0.3em 0" }}>{children}</ul>
          ),
          li: ({ children }) => (
            <li className="flex gap-1.5 items-start" style={{ color: P.textMuted }}>
              <span style={{ color: P.goldLight, fontSize: "8px", marginTop: "6px" }}>◆</span>
              <span>{children}</span>
            </li>
          ),
        }}
      >
        {claim.text}
      </ReactMarkdown>
      <GradeBadge grade={claim.grade} onClick={() => setShowTooltip(!showTooltip)} />
      {showTooltip && <ClaimTooltip claim={claim} onClose={() => setShowTooltip(false)} />}
      {" "}
    </span>
  );
}

// ── Plain Text View (no badges, clean reading) ───────────────────────────

function PlainClaimsView({ claims }: { claims: AnnotatedClaim[] }) {
  const fullText = claims.map((c) => c.text).join(" ");

  return (
    <div
      className="text-[15px] leading-[1.8]"
      style={{
        color: "hsl(30, 12%, 78%)",
        textRendering: "optimizeLegibility",
      }}
    >
      <ReactMarkdown
        components={{
          p: ({ children }) => (
            <p className="mb-2 last:mb-0" style={{ lineHeight: "1.8" }}>{children}</p>
          ),
          strong: ({ children }) => (
            <strong style={{ color: P.text, fontWeight: 600 }}>{children}</strong>
          ),
          em: ({ children }) => (
            <em style={{ color: P.goldLight, fontStyle: "italic" }}>{children}</em>
          ),
          code: ({ children }) => (
            <code
              style={{
                background: "hsla(38, 30%, 30%, 0.2)",
                padding: "1px 5px",
                borderRadius: "4px",
                fontSize: "0.9em",
                color: P.goldLight,
              }}
            >
              {children}
            </code>
          ),
          ul: ({ children }) => (
            <ul style={{ listStyle: "none", paddingLeft: "0.5em", margin: "0.3em 0" }}>{children}</ul>
          ),
          li: ({ children }) => (
            <li className="flex gap-1.5 items-start" style={{ color: P.textMuted }}>
              <span style={{ color: P.goldLight, fontSize: "8px", marginTop: "6px" }}>◆</span>
              <span>{children}</span>
            </li>
          ),
        }}
      >
        {fullText}
      </ReactMarkdown>
    </div>
  );
}

// ── Annotated Response Renderer ───────────────────────────────────────────

interface AnnotatedResponseProps {
  claims: AnnotatedClaim[];
  overallGrade: EpistemicGrade;
  iterations: number;
  converged: boolean;
  curvature: number;
}

export default function AnnotatedResponse({
  claims,
  overallGrade: grade,
  iterations,
  converged,
  curvature,
}: AnnotatedResponseProps) {
  const [showChainOfThought, setShowChainOfThought] = useState(false);
  const style = GRADE_STYLES[grade];
  const groundedCount = claims.filter((c) => c.grade <= "B").length;
  const lowTrust = isLowTrust(grade);

  return (
    <div className="space-y-3" style={{ fontFamily: P.font }}>
      {/* ── Low Trust Advisory. prominent when grade is C or D ──── */}
      {lowTrust && (
        <LowTrustAdvisory
          grade={grade}
          claims={claims}
          converged={converged}
          curvature={curvature}
        />
      )}

      {/* Response content. plain by default, annotated when toggled */}
      {showChainOfThought ? (
        <>
          <div
            className="text-[15px] leading-[1.8]"
            style={{
              color: "hsl(30, 12%, 78%)",
              textRendering: "optimizeLegibility",
            }}
          >
            {claims.map((claim, i) => (
              <AnnotatedClaimView key={i} claim={claim} delay={i * 80} />
            ))}
          </div>

          {/* Proof summary. minimal, warm, trustworthy */}
          <div
            className="flex items-center gap-4 text-[10px] tracking-wider pt-3 flex-wrap"
            style={{
              borderTop: `1px solid ${P.border}`,
              fontFamily: P.font,
            }}
          >
            <span
              className="flex items-center gap-1.5 px-2 py-1 rounded-md font-medium"
              style={{
                background: style.bg,
                color: style.color,
                letterSpacing: "0.1em",
              }}
            >
              <span style={{ fontSize: "8px" }}>{style.icon}</span>
              Grade {grade}
            </span>
            <span style={{ color: P.textDim }}>
              {iterations} {iterations === 1 ? "pass" : "passes"}
            </span>
            <span style={{ color: P.textDim }}>
              κ {(curvature * 100).toFixed(0)}%
            </span>
            <span style={{ color: converged ? GRADE_STYLES.A.color : GRADE_STYLES.C.color }}>
              {converged ? "✓ converged" : "refining…"}
            </span>
            <span className="ml-auto" style={{ color: P.textDim }}>
              {groundedCount}/{claims.length} grounded
            </span>
          </div>
        </>
      ) : (
        <PlainClaimsView claims={claims} />
      )}

      {/* Toggle button. always visible at the bottom */}
      <button
        onClick={() => setShowChainOfThought((v) => !v)}
        className="flex items-center gap-2 px-3 py-2 rounded-xl text-[12px] font-medium transition-all duration-200 w-full justify-center group"
        style={{
          background: showChainOfThought
            ? "hsla(38, 30%, 40%, 0.12)"
            : "hsla(38, 15%, 30%, 0.08)",
          border: `1px solid ${showChainOfThought ? "hsla(38, 30%, 50%, 0.2)" : "hsla(38, 15%, 30%, 0.12)"}`,
          color: showChainOfThought ? P.goldLight : P.textMuted,
          fontFamily: P.font,
          letterSpacing: "0.03em",
        }}
        onMouseEnter={(e) => {
          e.currentTarget.style.background = "hsla(38, 30%, 40%, 0.15)";
          e.currentTarget.style.borderColor = "hsla(38, 30%, 50%, 0.25)";
        }}
        onMouseLeave={(e) => {
          e.currentTarget.style.background = showChainOfThought
            ? "hsla(38, 30%, 40%, 0.12)"
            : "hsla(38, 15%, 30%, 0.08)";
          e.currentTarget.style.borderColor = showChainOfThought
            ? "hsla(38, 30%, 50%, 0.2)"
            : "hsla(38, 15%, 30%, 0.12)";
        }}
      >
        <Shield
          className="w-3.5 h-3.5 transition-colors"
          style={{ color: showChainOfThought ? style.color : P.textDim }}
        />
        <span>
          {showChainOfThought ? "Hide" : "View"} chain of thought
        </span>
        <span
          className="flex items-center gap-1 px-1.5 py-0.5 rounded text-[10px]"
          style={{
            background: style.bg,
            color: style.color,
          }}
        >
          {style.icon} {grade}
        </span>
        <span style={{ color: P.textDim }}>
          · {groundedCount}/{claims.length} verified
        </span>
        {showChainOfThought ? (
          <ChevronUp className="w-3 h-3 ml-auto" style={{ color: P.textDim }} />
        ) : (
          <ChevronDown className="w-3 h-3 ml-auto" style={{ color: P.textDim }} />
        )}
      </button>
    </div>
  );
}
