/**
 * UOR Foundation v2.0.0 — kernel::op
 *
 * 10 primitive operations, dihedral symmetry, the critical identity,
 * and the canonical OP_META table.
 * v0.2.0 additions: DispatchOperation, SessionCompositionOperation,
 * LiftOperation, ReductionOperation, ParallelOperation, OperationChain.
 *
 * @see foundation/src/kernel/op.rs
 * @namespace op/
 */

import type { PrimitiveOp, GeometricCharacter } from "../enums";
import type { Datum } from "./schema";

// ── Core Operation Types ───────────────────────────────────────────────────

export interface Operation {
  name(): PrimitiveOp;
  geometricCharacter(): GeometricCharacter;
  isInvolution(): boolean;
  isCommutative(): boolean;
  arity(): number;
}

/** UnaryOp — operation on a single ring element. */
export interface UnaryOp extends Operation {
  apply(x: Datum): Datum;
}

/** BinaryOp — operation on two ring elements. */
export interface BinaryOp extends Operation {
  apply(x: Datum, y: Datum): Datum;
}

/** Involution — a unary operation where f(f(x)) = x for all x. */
export interface Involution extends UnaryOp {
  isInvolution(): true;
}

/** IdentityOp — the identity operation. */
export interface IdentityOp extends UnaryOp {
  name(): "Neg";
  isInvolution(): true;
}

/** Group — abstract algebraic group. */
export interface Group {
  order(): bigint;
  generators(): PrimitiveOp[];
}

/** DihedralGroup — D_{2^n} symmetry group generated by (neg, bnot). */
export interface DihedralGroup extends Group {
  generators(): ["Neg", "Bnot"];
  presentation(): string;
  quantum(): number;
}

// ── Named Individuals ──────────────────────────────────────────────────────

export const CRITICAL_IDENTITY = {
  "@id": "op:critical_identity",
  forAll: "x ∈ R_n",
  lhs: "Succ" as PrimitiveOp,
  rhs: ["Neg", "Bnot"] as [PrimitiveOp, PrimitiveOp],
  equation: "neg(bnot(x)) = succ(x)",
} as const;

export const D2N = {
  "@id": "op:d2n",
  generatedBy: ["Neg", "Bnot"] as [PrimitiveOp, PrimitiveOp],
  presentation: "⟨r, s | r^{2^n} = s² = e, srs = r⁻¹⟩",
} as const;

export const OP_GEOMETRY: Record<PrimitiveOp, GeometricCharacter> = {
  Neg:  "RingReflection",
  Bnot: "HypercubeReflection",
  Succ: "Rotation",
  Pred: "RotationInverse",
  Add:  "Translation",
  Sub:  "Translation",
  Mul:  "Scaling",
  Xor:  "HypercubeTranslation",
  And:  "HypercubeProjection",
  Or:   "HypercubeJoin",
};

// ── OP_META ────────────────────────────────────────────────────────────────

export interface OpMeta {
  arity: 1 | 2;
  isCommutative: boolean;
  isInvolution: boolean;
  character: GeometricCharacter;
}

export const OP_META: Record<PrimitiveOp, OpMeta> = {
  Neg:  { arity: 1, isCommutative: false, isInvolution: true,  character: "RingReflection" },
  Bnot: { arity: 1, isCommutative: false, isInvolution: true,  character: "HypercubeReflection" },
  Succ: { arity: 1, isCommutative: false, isInvolution: false, character: "Rotation" },
  Pred: { arity: 1, isCommutative: false, isInvolution: false, character: "RotationInverse" },
  Add:  { arity: 2, isCommutative: true,  isInvolution: false, character: "Translation" },
  Sub:  { arity: 2, isCommutative: false, isInvolution: false, character: "Translation" },
  Mul:  { arity: 2, isCommutative: true,  isInvolution: false, character: "Scaling" },
  Xor:  { arity: 2, isCommutative: true,  isInvolution: false, character: "HypercubeTranslation" },
  And:  { arity: 2, isCommutative: true,  isInvolution: false, character: "HypercubeProjection" },
  Or:   { arity: 2, isCommutative: true,  isInvolution: false, character: "HypercubeJoin" },
};

// ══════════════════════════════════════════════════════════════════════════
// v0.2.0 ADDITIONS
// ══════════════════════════════════════════════════════════════════════════

/**
 * DispatchOperation — a dynamically dispatched operation selected at
 * runtime via a predicate dispatch table (kernel::predicate).
 *
 * @see spec/src/namespaces/op.rs — DispatchOperation
 */
export interface DispatchOperation extends Operation {
  /** Dispatch table identifier. */
  dispatchTableId(): string;
  /** Number of dispatch cases. */
  caseCount(): number;
  /** The operation selected for a given input. */
  dispatchFor(value: number): PrimitiveOp;
}

/**
 * SessionCompositionOperation — an operation that composes two
 * session contexts, merging their bindings under conflict rules.
 *
 * @see spec/src/namespaces/op.rs — SessionCompositionOperation
 */
export interface SessionCompositionOperation extends Operation {
  /** Conflict resolution strategy ("LeftWins" | "RightWins" | "Fail"). */
  conflictResolution(): "LeftWins" | "RightWins" | "Fail";
  /** Number of binding conflicts detected. */
  conflictCount(): number;
}

/**
 * LiftOperation — lifts a ring operation from quantum level Q_i
 * to quantum level Q_j (Q_j > Q_i).
 *
 * @see spec/src/namespaces/op.rs — LiftOperation
 */
export interface LiftOperation extends Operation {
  /** Source quantum level. */
  sourceQuantum(): number;
  /** Target quantum level. */
  targetQuantum(): number;
  /** The base operation being lifted. */
  baseOperation(): PrimitiveOp;
  /** Whether the lift is faithful (preserves all properties). */
  isFaithful(): boolean;
}

/**
 * ReductionOperation — a single step in the reduction pipeline.
 * Applies a rewrite rule to transform a term.
 *
 * @see spec/src/namespaces/op.rs — ReductionOperation
 */
export interface ReductionOperation extends Operation {
  /** Rewrite rule applied. */
  rule(): string;
  /** Whether this step is confluent. */
  isConfluent(): boolean;
  /** Term size before reduction. */
  sizeBefore(): number;
  /** Term size after reduction. */
  sizeAfter(): number;
}

/**
 * ParallelOperation — executes independent operations in parallel
 * over disjoint fiber budgets.
 *
 * @see spec/src/namespaces/op.rs — ParallelOperation
 */
export interface ParallelOperation extends Operation {
  /** Child operations. */
  children(): Operation[];
  /** Fiber budget partition identifiers. */
  budgetPartitions(): string[];
  /** Whether all children operate on disjoint fibers. */
  isDisjoint(): boolean;
}

/**
 * OperationChain — a composed sequence of operations applied left-to-right.
 * f₁ ∘ f₂ ∘ … ∘ fₙ
 *
 * @see spec/src/namespaces/op.rs — OperationChain
 */
export interface OperationChain {
  /** Chain identifier. */
  chainId(): string;
  /** Ordered operations. */
  operations(): Operation[];
  /** Chain length. */
  length(): number;
  /** Whether the chain is associative (all sub-compositions associative). */
  isAssociative(): boolean;
  /** Net geometric character of the composed chain. */
  netCharacter(): GeometricCharacter;
}
